### ISSUE TITLE
Image clibpboard support

### ISSUE THREAD

**Issue by BadKiko** [Jeffser/Alpaca#101]
It would be cool to have a feature to insert images from the clipboard into messages. This feature will allow users to easily share images within the app without having to save them to a file and then upload them manually.

**Comment by Jeffser** [comment]
Hi, thanks for the suggestion, once I get some free time I will work on this

**Comment by dodollama** [comment]
this is a nice feature to have

**Comment by Jeffser** [comment]
Hi I just implemented this feature for the next big release!

https://github.com/Jeffser/Alpaca/commit/4994f6d17725c9df7f860cd4c1f4cfe59adba26c
