### ISSUE TITLE
better visual appearance for downloading models with a better progress bar

### ISSUE THREAD

**Issue by olumolu** [Jeffser/Alpaca#102]
Show how the model is downloading in a better visual way possible 
![Screenshot_20240607-094845~3](https://github.com/Jeffser/Alpaca/assets/162728301/4ed788dd-02c1-454b-bf88-a8361323058a)
This is a example.

**Comment by Jeffser** [comment]
Hi thanks for the suggestion, that example looks great, I will try to make the progress bar more prevalent but I'm kinda limited by Adwaita, I will try to do it tho

**Comment by Jeffser** [comment]
I made a slight redesign of this for the next release

![image](https://github.com/Jeffser/Alpaca/assets/69224322/c7632100-03c0-452d-a145-57dbe8b7a091)

**Comment by dodollama** [comment]
> I made a slight redesign of this for the next release
> 
> ![image](https://private-user-images.githubusercontent.com/69224322/344502632-c7632100-03c0-452d-a145-57dbe8b7a091.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MDc1NDAsIm5iZiI6MTcxOTgwNzI0MCwicGF0aCI6Ii82OTIyNDMyMi8zNDQ1MDI2MzItYzc2MzIxMDAtMDNjMC00NTJkLWExNDUtNTdkYmU4YjdhMDkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA0MTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzY2U5NzU3YjU4YmZkNjk0MGIzZWVkM2E1ZjY1NTA4NjUyMGI2NDc5NzYwOWU2MDdmYWNmNGE0Y2RmNTAyM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.auwQgcWIHKU6f5dQormfXwnEowg7lH44A6WBNnyxvoQ)

This is kind of same but looks good can you shift this to bottom left of the sidebar it will be visually nicer and will make it awesome. Also when it become squeezed mobile friendly you can show the same in a small rounded way.

**Comment by Jeffser** [comment]
I might or might not put the models that are being pulled on the sidebar, but I won't put already pulled or stared models there, that's what the selector at the top of the window is for

**Comment by dodollama** [comment]
Ok but still i think it will look better and easy if the downloading progress is shown in the side bar

And also i ask you please add some eaual padding in the bottom part of the downloading progress bar so it can be done by just make the area bigger. And enlarge the progress bar not length wise rather width of the progress bar. With rounded ends.

**Comment by olumolu** [comment]
https://gitlab.gnome.org/-/project/11884/uploads/aa85a77acd65e0ea9fe1b0525415e274/image.png

**Comment by Jeffser** [comment]
I didn't want to make it public here since I first need to check with the Gnome Circle guys but yeah, I can move the list of models being pulled to the sidebar

**Comment by Jeffser** [comment]
I'm happy with the appearance since I changed it a couple of versions ago, I'll close this
