### ISSUE TITLE
Selecting options scrolls screen

### ISSUE THREAD

**Issue by youpie** [Jeffser/Alpaca#104]
**Describe the bug**
When hovering over options (like selecting image or plain text file) while the view is scrolled up. The screen will scroll down. This is the same issue as [this one from gnome calendar](https://gitlab.gnome.org/GNOME/gnome-calendar/-/issues/915)

**Expected behavior**
The view should not scroll

**Screenshots**
https://github.com/Jeffser/Alpaca/assets/37704067/a012a245-86c8-42e1-8f84-86281a013721

**Comment by Jeffser** [comment]
Hi, thanks for the report, I'm not sure how this happens seeing as it's also an issue on Gnome Calendar I think it might be a GTK / Adwaita problem

**Comment by Jeffser** [comment]
I just removed that menu completely for the next version, so let's say it's fixed haha
