### ISSUE TITLE
Alpaca Flatpak and Ollama server running in the background all the time

### ISSUE THREAD

**Issue by henriquead7** [Jeffser/Alpaca#106]
**Bug Description**

After closing Alpaca, even with the option to run in the background turned off, Alpaca and the Ollama server remain in the background consuming GPU resources, such as VRAM. This bug has already been reported in [issue 75](https://github.com/jeffser/alpaca/issues/75) (**closed**).

**Expected behavior**

Close Alpaca, and both it and the Ollama server would be terminated, freeing up the GPU. And it would run in the background only when the option is selected in the app.

**Screenshots**

Video demonstrating the Alpaca running in the background, even though it is completely shut down.

https://github.com/Jeffser/Alpaca/assets/56042159/dae0db3c-b337-447f-9b66-5ec7b11b8fac

I apologize for any inconvenience, but I had reported it in the closed issue. I believe you didn’t see it because it was already closed. That wasn’t my intention (And congratulations for your work, Alpaca is a great app 😊 ).

**Additional context**

System: Fedora Workstation 40
Flatpak version: 1.15.8
Alpaca version: 0.9.5
GPU: Nvidia GTX 1060
Nvidia driver: 550.90.07
CUDA: 12.4

**Comment by Jeffser** [comment]
Hi, thanks for the report, there is an option on the preferences menu on Alpaca to keep Alpaca open in the background if you close the app, maybe that's it?

**Comment by henriquead7** [comment]
This option is unchecked, in the video I demonstrate it (but my interface is in PT-BR)

**Comment by dodollama** [comment]
I have also faced this issue after closing the app and i can verify that i have not turned on the running in background option.
But i find that there are some issues while clearing the chat while dealing with this issue i found out that ollama.server is still running in the background if you open that app once you will be running that all the time.
Using 1.6gb ram for my system.
Can this problem be solved for next major release.

**Comment by Jeffser** [comment]
I changed the code so that the Ollama instance gets terminated instead of killed, maybe this will fix it, I don't see Ollama in the background when I close it

https://github.com/Jeffser/Alpaca/commit/e81d918675896c1670cf5aa5a55e1b706be5ed51
