### ISSUE TITLE
New logo ?

### ISSUE THREAD

**Issue by topiga** [Jeffser/Alpaca#109]
Hey, since you liked the logo I made for my theme, I figured out I would do one for here as well. If you don't like it, don't put it here, I really don't want to force you to do anything.
Anyway, here is the logo I made :
![com jeffser Alpaca(1)](https://github.com/Jeffser/Alpaca/assets/38886040/6d698353-72aa-4a25-8719-9cac661dec21)
For reference, this is the logo I made for my icon theme :
![com jeffser Alpaca](https://github.com/Jeffser/Alpaca/assets/38886040/c305db2e-44ad-4ae0-b544-0d4c668f0fcc)

If you want to put it in your app, you can, also if you want to make some changes, I can give you the svg version.

**Comment by userforsource** [comment]
can you provide vector of that image

**Comment by Jeffser** [comment]
Hi, tanks for the logo it looks great, I will need the SVG since it's required, great job!

**Comment by Jeffser** [comment]
Hi again, thanks for the icon, I was talking with the [Gnome Circle team](https://gitlab.gnome.org/Teams/Circle/-/issues/230), someone mentioned that the icon itself isn't Gnome'ish enough and I kinda see it, I might need to go with another icon from [this](https://gitlab.gnome.org/Teams/Design/app-icon-requests/-/issues/55) request, again, I'm thankful for the icon but I won't use it unfortunately

**Comment by userforsource** [comment]
If blue background is removed this can be a gnome app logo without a issue i think.
