### ISSUE TITLE
Add editing of prior messages

### ISSUE THREAD

**Issue by imbev** [Jeffser/Alpaca#11]
It would be very useful if all prior sent messages could be edited.

**Comment by Jeffser** [comment]
On it, thanks for the suggestion

**Comment by Jeffser** [comment]
I've been trying to wrap my head around how to do this, one thing is deleting messages but editing involves regenerating the output from the AI and stuff like that

**Comment by imbev** [comment]
I don't think that regeneration of AI output is necessary immediately following the edit. The edit should be a visual change, and impact future message generation.

**Comment by Jeffser** [comment]
I finally did it!

https://github.com/Jeffser/Alpaca/commit/7e4f1b25eea1e653a1417b5e478654fd5277573f
