### ISSUE TITLE
stable diffusion in alpaca

### ISSUE THREAD

**Issue by userforsource** [Jeffser/Alpaca#111]
https://huggingface.co/stabilityai/stable-diffusion-3-medium
can we have stable diffusion  for image generation ollama cant do this as far as i know but if you can implement it this will be really nice.

**Comment by Jeffser** [comment]
Hi thanks for the suggestion, for now I will not add this because it would involve using different tools other than Ollama, afaik Ollama is working on implementing these types of models so I'll just wait for that
