### ISSUE TITLE
There's a bug in alpaca where a chat that's renamed before it's used doesn't work.

### ISSUE THREAD

**Issue by outerpasta** [Jeffser/Alpaca#113]
I'm on Fedora workstation 40 and I downloaded from the Software app using Flathub.

I started a new chat and renamed it from 'New Chat' to something else and it wouldn't let me submit my first question. I had to change the name back to 'New Chat' before it would work.

Steps:
1. Have created multiple chats and renamed them from 'New Chat #' to something else.
2. Create a new chat by hitting the plus button.
3. Rename the chat to something else.
4. Try to submit a prompt.
Expected result: The prompt gets submitted and there is a response generated.
Actual result: The prompt doesn't get submitted.

**Comment by Jeffser** [comment]
Hi thanks for the report, I'm not sure what could be causing this, I will take a look at it later this week

**Comment by Jeffser** [comment]
Hi again, I just fixed the issue, thanks for the report
https://github.com/Jeffser/Alpaca/commit/6ba790416caf633f1ca52754c35a387a0d5ffeda
(the commit is named '}' by mistake)
