### ISSUE TITLE
bearer token support

### ISSUE THREAD

**Issue by theoden8** [Jeffser/Alpaca#116]
Good afternoon,

It would greatly increase the usability for me (and many other self-hosters of ollama) if it were possible to use an authentication token. This would allow me to use ollama without `ssh -L` or `ssh -R` functionality.

It is already implemented in many clients for other platforms, and would be great to see it in Alpaca.

Kind regards

**Comment by Jeffser** [comment]
Hi thanks for the suggestion, I'm not quite sure how bearer token works on ollama, Alpaca directly talks to the server using the url, is the token something that needs to be parsed to the server on the parameters?

**Comment by theoden8** [comment]
Essentially if you add to the header

```
authorization: Bearer $token
```

Then all proxies for ollama will be happy.

**Comment by Jeffser** [comment]
I did it
https://github.com/Jeffser/Alpaca/commit/527f7b445253775c98bb47affad89314e1b49856

But I don't have a way to test it so once it gets released on the next version please report it if it doesn't work, thanks

**Comment by theoden8** [comment]
I tried building the preview it with gnome-builder but receiving:

```
Error: module python3-pillow: Child process exited with code 137
```

I'll wait for the next release

**Comment by theoden8** [comment]
It works but you have to save bearer token first and then the site, I think.
