### ISSUE TITLE
search option for alpaca app in the model section

### ISSUE THREAD

**Issue by dodollama** [Jeffser/Alpaca#118]
there is no option to search models in alpaca if i need a model which is listed in the last part of the list this is really hard to find the model i want so search option is really a awesome feature.

**Comment by Jeffser** [comment]
Hi thanks for the suggestion, I'm currently working on it

**Comment by userforsource** [comment]
Thanks for that.

**Comment by Jeffser** [comment]
it is ready for the next release!
