### ISSUE TITLE
intregrated gpu is not suppoted i find this is slow for my system

### ISSUE THREAD

**Issue by dodollama** [Jeffser/Alpaca#120]
for systems having a decent graphics integrated which is now all of the devices coming with amd or intel.
you can play games with that also so it is important to use this and also if possible use npu which is available in new intel and ryzen cpus

**Comment by Jeffser** [comment]
Depending on which iGPU it is, it might not work with Ollama, this goes beyond the scope of Alpaca, though there's some people that have been having issues with some AMD GPUs specifically on Alpaca,  I'm working on that
