### ISSUE TITLE
add odf format

### ISSUE THREAD

**Issue by olumolu** [Jeffser/Alpaca#122]
http://opendocumentformat.org
Add odf format in alpaca

**Comment by Jeffser** [comment]
can it be converted to plain text?

**Comment by dodollama** [comment]
Yes`odt2txt` does this and i find now a days in many users use libreoffice which default to use odf.

**Comment by Jeffser** [comment]
alright I might add it

**Comment by Jeffser** [comment]
odt2txt was last updated 7 years ago, I rather not use it, it isn't even in PIP

**Comment by dodollama** [comment]
> odt2txt was last updated 7 years ago, I rather not use it, it isn't even in PIP

https://opendocumentformat.org/contact/
can you contact them they can help you.i cant find anything better or alternative at the point of time

**Comment by dodollama** [comment]
https://github.com/unoconv/unoconv
maybe this

**Comment by dodollama** [comment]
i think ai can help here i asked one 
```
Here's a Python implementation using the zipfile and xml.etree.ElementTree modules to extract the text from an ODT file:

python

import zipfile
import xml.etree.ElementTree as ET

def odt_to_txt(odt_file_path, txt_file_path):
    with zipfile.ZipFile(odt_file_path) as odt_zip:
        content_xml = odt_zip.read('content.xml')
        root = ET.fromstring(content_xml)
        text_elements = root.findall('.//{http://openoffice.org/2004/office/ods}p')
        text = '\n'.join([element.text for element in text_elements if element.text])
        with open(txt_file_path, 'w') as txt_file:
            txt_file.write(text)

# Example usage:
odt_to_txt('input.odt', 'output.txt')

This script extracts the text from the content.xml file inside the ODT archive, which contains the document's content. It then writes the extracted text to a new TXT file.
```

**Comment by dodollama** [comment]
i find this in internet.

**Comment by dodollama** [comment]
> odt2txt was last updated 7 years ago, I rather not use it, it isn't even in PIP

This is a simple program i don't think it is a big issue for such. I was reading that. I did not find anything wrong. We might use that without any issue.

**Comment by olumolu** [comment]
> odt2txt was last updated 7 years ago, I rather not use it, it isn't even in PIP

Do you think it might be possible to add else close this request is the best option left

**Comment by Jeffser** [comment]
Alpaca is now able to attach Odt files (ODF text document, LibreOffice Writter)

https://github.com/Jeffser/Alpaca/commit/c32c2e22c91311742611dcb5db3fbecd3538a9f0

It recognizes paragraphs, headings and tables!

**Comment by olumolu** [comment]
Thanks for consideration.
I think you can still consider use odfdo it is just a drop in replacement and with a updated and maintained library...
I would love to know why you think odfpy is a better choice rather than odfdo.

**Comment by Jeffser** [comment]
cause I already did it with odfpy and I don't like redoing work when it's needed, that's all

Like I said before in the commit, I will use odfdo if I ever need to do anything more complex than just extracting text from a text document

**Comment by olumolu** [comment]
> cause I already did it with odfpy and I don't like redoing work when it's needed, that's all
> 
> Like I said before in the commit, I will use odfdo if I ever need to do anything more complex than just extracting text from a text document

I understand.

**Comment by Jeffser** [comment]
Whatever, I ported it

https://github.com/Jeffser/Alpaca/commit/789157cb9437e0b1ebd6833b88056709ebd187f1

**Comment by Jeffser** [comment]
just so you know, I reverted the code to odfpy

https://github.com/Jeffser/Alpaca/commit/0af492b079b8305e26245294b0329061bc2d5fdf

Should have tested it before using odfdo, it doesn't define correctly one of it's dependencies and causes an error when trying to make a Flatpak package.
