### ISSUE TITLE
I can make a Norwegian translation

### ISSUE THREAD

**Issue by CounterFlow64** [Jeffser/Alpaca#123]
**Is your feature request related to a problem? Please describe.**

No, but the more translations the better

**Describe the solution you'd like**

I can contribute a Norwegian translation

**Additional context**

Something like Weblate would make translation easier. I'm not familiar with git or code, do I just look for words and translate them?

https://weblate.org/en/

**Comment by Jeffser** [comment]
Hi, I really don't have the time to set up weblate, but if you want to you can checkout [this file](https://github.com/Jeffser/Alpaca/blob/main/po/fr.po), that's the French translation, if you feel comfortable with working with a .po file I can set up a Norwegian file for you

**Comment by CounterFlow64** [comment]
That looks workable. I can give it a try.

**Comment by Jeffser** [comment]
Just to make sure which language code to use, it is Norway Norwegian right?

**Comment by CounterFlow64** [comment]
Yes, or Norwegian Bokmål. We have two written language dialects, I write Bokmål.
