### ISSUE TITLE
Mark models tags as unsupported when it applies on the system

### ISSUE THREAD

**Issue by olumolu** [Jeffser/Alpaca#128]
like assume someone wants to run deepseek v2 234B model in there system which have only 8/16/32 ram this can enhance the user experience by leaps and bounce.

**Comment by Jeffser** [comment]
Hi, thanks for the suggestion, I will think about it

**Comment by botollama** [comment]
thanks for that
i can run a 8b model in a 8gb laptop running fedora
and a 16b deepseek v2 on 16ram server running alma

**Comment by Jeffser** [comment]
I won't do this because there's not an easy way to check if a model is compatible or not before downloading
