### ISSUE TITLE
Code formatting on responses

### ISSUE THREAD

**Issue by olumolu** [Jeffser/Alpaca#129]
here is a example of duckduckgo chat interface 
![image](https://github.com/Jeffser/Alpaca/assets/162728301/172cdab3-4d8b-448f-af2b-a22d75bdcfad)
not only here major all chat services provide this.

**Comment by loulou64490** [comment]
this is already implemented 
![Capture d’écran du 2024-07-06 19-19-09](https://github.com/Jeffser/Alpaca/assets/102870297/3ad82de7-71d6-4d87-8eba-b2d6b0d94602)

**Comment by Jeffser** [comment]
It has been implemented but some models don't follow the standard output for code
```
```PYTHON
print('hello world')
```
```

Instead they do this

```
`
print('hello world')
`
```

I might also add that as a format

**Comment by Jeffser** [comment]
Hi I just got around fixing this, sorry for the wait

https://github.com/Jeffser/Alpaca/issues/166
