### ISSUE TITLE
Add deletion of prior messages

### ISSUE THREAD

**Issue by imbev** [Jeffser/Alpaca#13]
It would be useful for the user to be able to delete messages per-message

**Comment by Jeffser** [comment]
Sure, I can do that, thanks

**Comment by Jeffser** [comment]
I was thinking about this, should I make it so that the user can only delete their own messages or also the bot's OR delete the user message AND the response to that particular message?

**Comment by imbev** [comment]
The ability to delete any message regardless of sender would be most useful. Sometimes the user accidentally sends the wrong message.

**Comment by imbev** [comment]
This would also overlap with potentially regenerating the bot's most recent response

**Comment by Jeffser** [comment]
I finally got around to doing this, thanks for the suggestion
https://github.com/Jeffser/Alpaca/commit/db0daa1f4114946aa0a4212df8cf188db2442f86
