### ISSUE TITLE
output in a table or spreedsheet format when it is asked specifically 

### ISSUE THREAD

**Issue by olumolu** [Jeffser/Alpaca#131]
this is something very important like ask something and to ai and show in a spreedsheet format as humans are good at viewing them
example
![image](https://github.com/Jeffser/Alpaca/assets/162728301/b6225f5a-ea38-49e0-a2d6-518e545f71cf)

**Comment by Jeffser** [comment]
Hi, unfortunately neither Adwaita nor GTK4 have a widget for tables, I would have to create that manually, so it's going to take a long time
