### ISSUE TITLE
add a welcome screen

### ISSUE THREAD

**Issue by olumolu** [Jeffser/Alpaca#137]
if there is no chat we should have a welcome screen where we have 3-4 options to start with
and add a alpaca brand logo just in the middle of the screen and will be vanished on first chat. i think this will add a depth on the application.
i find a similar mock up in the issues section which can be considered. [mockup](https://private-user-images.githubusercontent.com/102870297/335127287-5b9d8cdb-bbd7-4d0e-af34-11aabff1faa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NDI5NDcsIm5iZiI6MTcyMDQ0MjY0NywicGF0aCI6Ii8xMDI4NzAyOTcvMzM1MTI3Mjg3LTViOWQ4Y2RiLWJiZDctNGQwZS1hZjM0LTExYWFiZmYxZmFhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQxMjQ0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjg4ZGMyMmQzYWQ1MTk5OTgwY2RjYWM1ZDFhMTgyNzc1NTcyNDg5ZjA1YjhiZjNkYmQ0NGNkODM0ZjA5NWYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.593ypPRRtR5eV8LlsByJwIQdGIowYptFvpYdSxTYZjs) by @loulou64490

**Comment by loulou64490** [comment]
I already proposed this https://github.com/Jeffser/Alpaca/issues/70

**Comment by loulou64490** [comment]
![welcome](https://github.com/Jeffser/Alpaca/assets/102870297/5b9d8cdb-bbd7-4d0e-af34-11aabff1faa4)

**Comment by olumolu** [comment]
import gi
gi.require_version("Gtk", "4.0")
from gi.repository import Gtk

class MyWindow(Gtk.Window):
    def __init__(self):
        super().__init__(title="Alpaca")
        self.set_default_size(800, 600)
        
        # Other initializations and widget setups

        # Show the welcome message dialog when the application starts
        self.show_welcome_dialog()

    def show_welcome_dialog(self):
        dialog = Gtk.MessageDialog(
            transient_for=self,
            modal=True,
            buttons=Gtk.ButtonsType.OK,
            message_type=Gtk.MessageType.INFO,
            text="Welcome!",
        )
        dialog.format_secondary_text("Welcome to the alpaca!")

        # Add the logo image to the dialog
        image = Gtk.Image.new_from_file(data/icons/com.jeffser.Alpaca.Source.svg")
        dialog.set_image(image)

        dialog.run()
        dialog.destroy()

def main():
    win = MyWindow()
    win.connect("destroy", Gtk.main_quit)
    win.show()
    Gtk.main()

if __name__ == "__main__":
    main()
I got this using deepseek v2 236b

**Comment by olumolu** [comment]
@Jeffser have you considered this to be implemented an welcome screen makes sense. Set random questions and system will any 3of it

**Comment by Jeffser** [comment]
The problem I have with the set of questions is the translations, there are some models that understand multiple languages and some that not, should I translate those questions or not? Does it make sense for the welcome screen and the whole app itself to be in french if the questions are in english?

**Comment by olumolu** [comment]
Make it english only now having support for other languages is not a issue here

In that case we can have multi language support ready for selected models which most users will use like llama gemma phi mistral qwen cohere deepseek.
This models are the best of all and most users if not all will use this models and for other than this model just don't show the suggested question

**Comment by loulou64490** [comment]
Translate the question, bc most models understand different languages, and when a user choose a particular model, he won't use the default question I think

**Comment by Jeffser** [comment]
yeah problem is that Alpaca is being translated to languages like Bengali and Norwegian, no offense to those languages but I don't think there are many models that understand them, and then again, there are a couple of Chinese only and English only models, as you can see, it is very inconsistent

**Comment by loulou64490** [comment]
okay, do whatever you want

**Comment by olumolu** [comment]
As far as i know bengali is supposed in all llama gemma and qwen phi models.i have not tested eith other if you want i can test and let you know..
I don't think that is a problem.

**Comment by Jeffser** [comment]
I didn't know that I just assumed that most models were English only, again, there are some that are English only or Chinese only, it is inconsistent and those prompts won't work all the time, it will be a bad look for a user to use one of those prompts and the model just not understanding, the user will think "But the app told me this was a valid prompt"

**Comment by olumolu** [comment]
I am testing aya by cohere dones not have support for bn

**Comment by Jeffser** [comment]
Ok since you guys keep asking for it, I'm going to add the welcome screen thing.

I'm currently written dome papers for college so it may take a week or two before the next version but I will add it

**Comment by Jeffser** [comment]
The prompts will be in english and that's the final decision, no translations

**Comment by Jeffser** [comment]
![image](https://github.com/user-attachments/assets/0de6a304-ff4a-47c2-8944-fce35728a395)

![image](https://github.com/user-attachments/assets/6262f4b5-eefe-4ff6-a949-6a538e79026d)

**Comment by Jeffser** [comment]
[it's done](https://github.com/Jeffser/Alpaca/commit/a9112cf3daa650cc79912d4c1ff65dff5adb127e)

Now, I'm not going to close this issue, I want to do something fun

I want you guys to give me some prompts you'd want to see added to the pool of random prompts, they can be serious or funny, just something that would make sense to start a conversation with a model

**Comment by olumolu** [comment]
Sure.

**Comment by Jeffser** [comment]
Also I added this message if the user doesn't have any models downloaded yet, I think this is a nice way of teaching the user that the model manager exists

![image](https://github.com/user-attachments/assets/32c4abda-763a-46ce-a6df-3c4f2ba90da6)

**Comment by Jeffser** [comment]
please use [this discussion](https://github.com/Jeffser/Alpaca/discussions/203)
