### ISSUE TITLE
Handle creating new chat without name

### ISSUE THREAD

**Issue by imbev** [Jeffser/Alpaca#14]
When creating a new chat, clicking create without entering a name will have the same effect as clicking cancel.

I suggest either using a default name such as "Untitled Chat" or keeping the modal open with a message.

**Comment by Jeffser** [comment]
Makes sense, I'm going to implement that, thanks for the suggestion

**Comment by Jeffser** [comment]
[Done](https://github.com/Jeffser/Alpaca/commit/f333f50016628e242914cef06958b0a9f89f7850)
Thanks for the suggestion!
