### ISSUE TITLE
share screen with models so it can give realtime help for the problems

### ISSUE THREAD

**Issue by olumolu** [Jeffser/Alpaca#145]
Like gpt4o like interface where it can provide help with
Share screen
Now some new model are coming up with gpt4 like capabilities.

**Comment by Jeffser** [comment]
I will think about it

**Comment by Jeffser** [comment]
I've decided to not try to do this, the models that have image recognition capabilities are way to slow to understand a constant stream of frames, even if it was slowed to 1 frame every 5 seconds, that would still be way too fast

**Comment by olumolu** [comment]
https://github.com/mediar-ai/screenpipe
