### ISSUE TITLE
support for snap

### ISSUE THREAD

**Issue by olumolu** [Jeffser/Alpaca#147]
Support for snap maybe a good option.

**Comment by Jeffser** [comment]
I considered this before but I'm not used to snapcraft and I don't want to run Ubuntu at the moment, as far as I know I would have to run Ubuntu on a virtual machine and that seems like a lot of work, not even Gnome packages their own apps on Snap, Cannonical does that for them, I don't see why I should support a package manager that is only used by Ubuntu and some other small distros.

Don't take this as a firm "I won't do that", it's just not something I want to do at the moment, it's not a priority

**Comment by olumolu** [comment]
Yes this is not for now but can be considered after this release.

**Comment by olumolu** [comment]
https://github.com/Jeffser/Alpaca/pull/291

**Comment by olumolu** [comment]
https://github.com/Jeffser/Alpaca/pull/305
