### ISSUE TITLE
support for image to solve maths and other problems

### ISSUE THREAD

**Issue by olumolu** [Jeffser/Alpaca#148]
Using ocr
https://github.com/ocrmypdf/OCRmyPDF
And from pdf to txt.
Maybe directly build ocr https://github.com/tesseract-ocr/tesseract
And solve maths problems with new mathstral or other good models.

**Comment by Jeffser** [comment]
In general most models can understand latex (a language made for math annotation), in case the user doesn't use that, llava can read text directly from images, I think that could be a solution for this problem
