### ISSUE TITLE
on fresh install download button model button does not work

### ISSUE THREAD

**Issue by olumolu** [Jeffser/Alpaca#158]
https://github.com/user-attachments/assets/4b8d67b4-95f5-49e3-9cf3-ecf1111919d5

**Comment by Jeffser** [comment]
It works for me on a fresh install, could you send me the output when running Alpaca using `flatpak run com.jeffser.Alpaca` ?

**Comment by olumolu** [comment]
https://github.com/user-attachments/assets/727edc39-3168-4547-b6c8-ffb44fde77ef


https://github.com/user-attachments/assets/d514ee46-cbe6-4bf7-bccb-d6959f080d1a

[a.txt](https://github.com/user-attachments/files/16364225/a.txt)
[open.txt](https://github.com/user-attachments/files/16364226/open.txt)

**Comment by Jeffser** [comment]
idk it looks like Ollama isn't accepting requests, reinstalling it completely might fix it

Make sure to remove ~/.var/app/com.jeffser.Alpaca

**Comment by olumolu** [comment]
I will take look into the issues.

**Comment by Jeffser** [comment]
Whilst I'm familiar with those languages, I'm a lot more comfortable with using Python, I don't feel like it would be that much faster either way

**Comment by olumolu** [comment]
But adding that maybe those who know that language can contribute.

**Comment by Jeffser** [comment]
I don't think it will make that much of a difference, Ollama will always slow down the app for obvious reasons, so it really doesn't matter if the message gets sent .2 seconds faster or something like that

**Comment by olumolu** [comment]
That is true though

**Comment by Jeffser** [comment]
Anyways I think I can mark this as done, this button doesn't even exists in the current version

**Comment by olumolu** [comment]
I will test this and let you know
