### ISSUE TITLE
Remote ollama connectivity check is not robust

### ISSUE THREAD

**Issue by ProjectMoon** [Jeffser/Alpaca#160]
**Describe the bug**
The way that the application attempts to check connectivity with ollama assumes it's connecting to ollama directly, or that whatever server it's connecting to will directly serve all bits of the ollama API. OpenWebUI, while it does proxy to the ollama API, does NOT serve the "endpoint" (not sure it can really be called that) that says `Ollama is running`. Connection to an OpenWebUI-proxied ollama server will thus not work.

I worked around this by making some nginx location entry blocks thusly:

```
location ~ ^/ollama/api/(.+)$ {
    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_set_header Origin '';
    proxy_set_header Referer '';
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_connect_timeout       3600;
    proxy_send_timeout          3600;
    proxy_read_timeout          3600;
    send_timeout                3600;

    # OpenWebUI is running on port 11435 locally.
    proxy_pass http://localhost:11435/ollama/api/$1;
}

# These blocks are for compatibility with Alpaca
# due to how it checks if ollama is running. OpenWebUI
# does not expose the root endpoint of ollama.
location = /ollama/api/ {
    return 200 'Ollama is running\n';
    add_header Content-Type text/plain;
}

location = /ollama/api {
    return 200 'Ollama is running\n';
    add_header Content-Type text/plain;
}

location = /ollama/ {
    return 200 'Ollama is running\n';
    add_header Content-Type text/plain;
}

location = /ollama {
    return 200 'Ollama is running\n';
    add_header Content-Type text/plain;
}
```

**Expected behavior**
The connection to any type of proxied ollama server or ollama-compatible API is validated correctly.

**Additional context**
It would probably be safer to do something like call the `tags` API to list models and check for HTTP 200 and make sure that the response is sane (i.e. empty list on a fresh ollama installation, or a list of models on existing installation of ollama).

Also notable information: when adding the connection to the OpenWebUI proxied API for the first time, Alpaca refuses to validate it, even with the above endpoints in place, for some reason. However, after closing and reopening, the application connects to it just fine.

**Comment by Jeffser** [comment]
you are absolutely right about this, I will be changing the server test to `/tags`, thanks for the report!

**Comment by Jeffser** [comment]
[Fixed!](https://github.com/Jeffser/Alpaca/commit/a765e8cf2ee0c8a0a51a540736e91f279deea2f9)

Thanks for the report!
