### ISSUE TITLE
Need Report from NVIDIA users

### ISSUE THREAD

**Issue by Jeffser** [Jeffser/Alpaca#161]
Hi, are you using Alpaca with a NVIDIA GPU?
Does it work?
Do you need to change permissions?

I don't have an NVIDIA GPU to test my app so it would be helpful if someone could tell me if it works, thanks <3

**Comment by GaPhilippone** [comment]
Hello, for me NVIDIA GPU seem to be working
![Screenshot from 2024-07-27 15-13-29](https://github.com/user-attachments/assets/92558f4d-7c82-48d5-b2b3-59c3c5b6973f)

**Comment by Jeffser** [comment]
Thank you!

**Comment by leukk** [comment]
Hi, seems to be working well out of the box.
![screenshot](https://github.com/user-attachments/assets/b16646f2-6cb6-4333-8a45-b64cc5511fcc)

**Comment by Jeffser** [comment]
Thanks!
