### ISSUE TITLE
Error Gemma 2

### ISSUE THREAD

**Issue by RicardoGausmann** [Jeffser/Alpaca#162]
Hello,
My name is Ricardo and I'm from Brazil.
I'm not able to run the Gemma 2 model versions on Alpaca.
Other AI models work normally.
What might be going wrong?

**Comment by RicardoGausmann** [comment]
![Captura de tela de 2024-07-24 01-14-55](https://github.com/user-attachments/assets/24359bc1-8adc-44a1-bc7e-ce0b15ac609a)

There was an error with the local Ollama instance, it was unconfigured.

**Comment by Jeffser** [comment]
Hi thanks for the report, I'm not sure why this happens but just close and reopen the app, it worked for me... for some reason, idk

**Comment by Jeffser** [comment]
since I haven't gotten any other reports I will close this, should be working
