### ISSUE TITLE
Pause & resume feature for model download

### ISSUE THREAD

**Issue by ecelia** [Jeffser/Alpaca#163]
If possible, a pause and resume feature for downloading big models would make sense.

**Comment by olumolu** [comment]
The issue is this feature is not available in ollama as ollama is the backend of this this seems to be extremely hard to implement i request you to also post a feature request in ollama github.
So it can be solved.

**Comment by ecelia** [comment]
Apparently an environment variable OLLAMA_NOPRUNE must be set for an api pull in order to resume downloads.

https://github.com/ollama/ollama/issues/2463#issuecomment-1938872167
https://github.com/ollama/ollama/issues/695#issuecomment-1749043351

**Comment by Jeffser** [comment]
yeah the problem with this is that, OLLAMA_NOPRUNE is meant to recover downloads that have being interrupted by the process dying or the computer turning off, it isn't possible to, let's say, pause one download and continue with another one at the same time. If Ollama includes an actual way of doing this I will add it, but as for now, there's nothing I can do
