### ISSUE TITLE
Allow using unlisted models from ollama

### ISSUE THREAD

**Issue by Aleksanaa** [Jeffser/Alpaca#164]
**Is your feature request related to a problem? Please describe.**

I want to try out the fresh new https://ollama.com/library/llama3.1:8b, but it's not listed, so I have to find a gguf file from huggingface before it's added to the list.

**Describe the solution you'd like**

Add a "From Unlisted Ollama Model (experimental)" to the add button of "Manage Models".

**Describe alternatives you've considered**
Listing unlisted models when searching.

**Comment by Jeffser** [comment]
Hi, the app is getting proper GGUF support on the next version that should be out in a couple of hours.

I also just added the option to pull models with just the name, for example "llama3.1:8b"

https://github.com/Jeffser/Alpaca/commit/e65a8bc6483792621b7ea1a488f6aad699383528
