### ISSUE TITLE
Error with Ollama instance

### ISSUE THREAD

**Issue by sjsaug** [Jeffser/Alpaca#165]
**Describe the bug**
When using certain models, for example Deepseek Coder V2, I receive the error following message: 'There was an error with the local Ollama instance, so it has been reset.". This does not occur when using something like Llama3.

**Expected behavior**
Ollama replies to my query.

**Screenshots**
[Screenshot](https://github.com/user-attachments/assets/fd542270-8ebc-4dd3-88b1-60397552094b)

**Additional context**
I have a 3090 with the proper drivers installed. Inference works fine w/ the Ollama cli.

**Comment by sjsaug** [comment]
Restarting the app does not fix this.

**Comment by Jeffser** [comment]
Hi, I think this is related to [this](https://github.com/Jeffser/Alpaca/issues/159)

If that's the case, it was fixed on 1.0.1

**Comment by sjsaug** [comment]
Hi, I was using version 1.0.1 when this bug occured.

**Comment by GaPhilippone** [comment]
Same for me. Deep Seek Coder V2 is not working. Llama3 is working

**Comment by GaPhilippone** [comment]
Resolved in 1.0.2. Issue can be closed for me
