### ISSUE TITLE
Output without "rendered" formatting  

### ISSUE THREAD

**Issue by leukk** [Jeffser/Alpaca#166]
**Describe the bug**
Models output is not being shown correctly. Contains markdown-like symbols that are not being applied.

**Expected behavior**
Output being rendered correctly, such as ``` code block ``` being shown as a code block element instead of  \``` code block ```.

![image](https://github.com/user-attachments/assets/372df1df-1d28-4e1c-a95e-c56661a75ceb)

**Additional context**
Downloaded from Flathub on Fedora 40, version 1.0.1. The issue doesn't seem to be model dependent.

**Comment by Jeffser** [comment]
Hi I will work on this

**Comment by Jeffser** [comment]
Hi I just [finished this](https://github.com/Jeffser/Alpaca/commit/c192a1f31cf8a341452995b35f4e441cce193ac8)!
When a model doesn't specify a language it just displays a generic code block, this means no code highlighting but it works the same as the normal code blocks.

![image](https://github.com/user-attachments/assets/549b5efc-87fa-445c-88b7-a12f7373cd76)

**Comment by leukk** [comment]
Awesome, you're doing a great job. Thanks!
