### ISSUE TITLE
Window is too tall for phone usage; chat box is blocked by osk.

### ISSUE THREAD

**Issue by ashrude** [Jeffser/Alpaca#167]
I'm using a Oneplus 6t running PostmarketOS with gnome-mobile-shell. When A textbox comes into focus the window is resized so that the bottom of the window is at the top of keyboard, however the height-request of alpaca is too large so the textbox gets hidden behind the keyboard.

<image src="https://github.com/user-attachments/assets/015f48b7-9cb8-4b3f-9bb4-1054f13e27d1" width="300px"/>
<image src="https://github.com/user-attachments/assets/a96682c8-4e83-4044-8a8c-b039d0dbf081" width="300px"/>

Changing the height-request to 500 should fix this, but it should be noted that the preferences dialog gets cut off at this size.

**Comment by Jeffser** [comment]
Hi, thanks for reporting this, I'm going to work on it!

**Comment by ashrude** [comment]
Cool. Lmk if you need me to test anything

**Comment by Jeffser** [comment]
Hi I just fixed this!

https://github.com/Jeffser/Alpaca/commit/02aa2734e094fae7f2ad28b263d58164a56617d5
![image](https://github.com/user-attachments/assets/a88379f0-7b70-4495-8311-076aae5d95a7)

**Comment by Jeffser** [comment]
if it doesn't work on the next version please reopen the issue, thanks
