### ISSUE TITLE
Connection Error when model tag contains a capital character

### ISSUE THREAD

**Issue by jaccokw** [Jeffser/Alpaca#168]
When trying to use a model that has a tag with a capital character, it fails with a "Connection Error".

It's related to lower-casing the model-name-and-tag in the file "src/window.py" in the functions "generate_chat_title" and "send_message". They contain a line like this:
current_model = current_model.replace(' (', ':').replace(' ', '-')[:-1].lower()

I solved it quick-and-dirty like this:
current_model = current_model.replace(' (', ':').replace(' ', '-')[:-1]
model, tag = current_model.split(':')
current_model = model.lower() + ':' + tag

It may be better to store the original model name and tag somewhere to prevent bugs due to rewriting.

**Comment by Jeffser** [comment]
Hi, correct me if I'm wrong but I think there aren't any models that have capital characters

**Comment by Jeffser** [comment]
welp I stand corrected, I will fix it

**Comment by Jeffser** [comment]
[This](https://github.com/Jeffser/Alpaca/commit/33e47696dc7de061af9567ce3a798b8372917efd) should fix the problem, thanks for the report
