### ISSUE TITLE
Setup Ollama within Flatpak sandbox

### ISSUE THREAD

**Issue by imbev** [Jeffser/Alpaca#17]
It might be possible to install Ollama locally within the Flatpak sandbox using the `extra-data`  source type.

I suggest that alongside the Ollama connect option, the user should have an option to "Setup sandboxed Ollama". Ollama could be downloaded in a similar manner to models, and be automatically started when the app launches if installed.

See:
https://docs.flatpak.org/en/latest/manifests.html#modules
https://github.com/ollama/ollama/blob/main/docs/linux.md

**Comment by Jeffser** [comment]
You know? someone told me something like that when I submitted the app to Flathub, it sounds kinda difficult but it would make the app easier to use for casual users. I'm going to work on it but no promises.

**Comment by Jeffser** [comment]
Hi I was trying to do this but to include extra-data we need the sha256 for the Ollama binary, problem is, Ollama doesn't provide that, or maybe they do but I haven't find it

**Comment by imbev** [comment]
It might be necessary to host a mirror of the file, perhaps through github pages are the internet archive.

I've had trouble using github releases as Flatpak sources.

**Comment by Jeffser** [comment]
It's working, I still don't know if Ollama keeps the models inside the sandbox tho
![image](https://github.com/Jeffser/Alpaca/assets/69224322/c06f6528-c0db-4836-9ad2-bda062510eef)

**Comment by Jeffser** [comment]
There's a problem. it keeps the models in ~/.ollama, I don't think I can change that

**Comment by Jeffser** [comment]
![image](https://github.com/Jeffser/Alpaca/assets/69224322/04e26e88-966a-4688-84ce-5f02afa37bdf)
I love how Linux works, I just changed the HOME variable for ollama and it worked hahahaha

**Comment by imbev** [comment]
That's great. Does `self.data_dir` correspond to `XDG_DATA_HOME`?

**Comment by Jeffser** [comment]
I just did something cool on accident, if you close the app while using the sandbox instance Alpaca keeps running on the background.
![image](https://github.com/Jeffser/Alpaca/assets/69224322/473c1514-9364-498d-b57b-c0ec77d56bb5)

**Comment by Jeffser** [comment]
> That's great. Does `self.data_dir` correspond to `XDG_DATA_HOME`?
yep that's it

**Comment by imbev** [comment]
That's useful. Perhaps there could also be an option to specify the host:port for Ollama to bind to in a preferences menu?

**Comment by Jeffser** [comment]
sure, I don't see why not, self.local_ollama is actually just "127.0.0.1:11435" so I could just change that value and reload the instance

**Comment by imbev** [comment]
I suggest that Alpaca prefer the sandboxed Ollama, but provide the connect to external Ollama (the current story) as a fallback.

**Comment by Jeffser** [comment]
Should I remove the 'setup' page in the welcome dialog then?

**Comment by imbev** [comment]
Yes, or replace the setup with a prompt to setup a featured model such as llama3:8b (with an option to skip)

**Comment by not-a-dev-stein** [comment]
Also, since it is now able to run in the background, may I suggest taking a look the [XDG Desktop API for it](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.background.Monitor.html) so you'd be able to put a nice subtitle on the program's actions in the background (for example, if it is closed while still generating an answer or just to state that the ollama server is running)?

I would open a separate issue for it, but since it's been mentioned here ¯\\_ (ツ)_/¯

**Comment by Jeffser** [comment]
sure, I'll take a look at it

**Comment by Jeffser** [comment]
It's still experimental but it kinda works
https://github.com/Jeffser/Alpaca/commit/69567d1c6c6099ce98e40a73d6c2249ed6d5f584
I will continue tomorrow or maybe later at night

**Comment by Jeffser** [comment]
Just submitted the new version to Flathub, if you want to try it before it goes public you can use this
`flatpak install https://dl.flathub.org/build-repo/105608/com.jeffser.Alpaca.flatpakref`
Btw the XDG API for backgroun description will have to wait until the next version
