### ISSUE TITLE
Alpaca not launching

### ISSUE THREAD

**Issue by gegentan** [Jeffser/Alpaca#170]
**Describe the bug**
After installing alpaca, it doesn't launch from the gnome software app or app overview. When running alpaca from warehouse, it outputs this error:

`
(process:2): Gtk-WARNING **: 11:49:49.469: Locale not supported by C library.
	Using the fallback 'C' locale.
Traceback (most recent call last):
  File "/app/bin/alpaca", line 45, in <module>
    from alpaca import main
  File "/app/share/Alpaca/alpaca/main.py", line 29, in <module>
    from .window import AlpacaWindow
  File "/app/share/Alpaca/alpaca/window.py", line 37, in <module>
    class AlpacaWindow(Adw.ApplicationWindow):
  File "/app/share/Alpaca/alpaca/window.py", line 47, in AlpacaWindow
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.11/locale.py", line 627, in setlocale
    return _setlocale(category, locale)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
locale.Error: unsupported locale setting
`

**Expected behavior**
It launches.

**Screenshots**
![image](https://github.com/user-attachments/assets/e45f8dc5-95e7-4f67-b414-c5131e520bdf)

**Additional context**
OS: Ubuntu 24.04
Alpaca version: 1.0.2

**Comment by Jeffser** [comment]
Hi, it looks like you are trying to run Alpaca with an incompatible locale, may I ask which language and region you are using on your system?

**Comment by gegentan** [comment]
I am using english as language and germany as region.

![image](https://github.com/user-attachments/assets/6bbb84e2-fedc-449e-9e50-41800223e577)

**Comment by gegentan** [comment]
After running `export LC_ALL="en_US.UTF-8` and starting alpaca via command line using `flatpak run com.jeffser.Alpaca` makes alpaca launch (But only from the command line).

**Comment by gegentan** [comment]
I don't know if this helps but

```
bruno@bruno-pc-ubuntu:~$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
bruno@bruno-pc-ubuntu:~$ 
```

**Comment by Jeffser** [comment]
well, my guess is that Ubuntu doesn't fill LC_ALL automatically, I'll make the app use the LANG variable as a fallback if I can figure out how to do that

**Comment by Jeffser** [comment]
turns out the line that was causing the issues wasn't needed at all, it should work fine now

https://github.com/Jeffser/Alpaca/commit/19b089e6c63c2b1e00ecee5d38915b18ff65fa2f
