### ISSUE TITLE
Allow building without embedded ollama server

### ISSUE THREAD

**Issue by jaredmontoya** [Jeffser/Alpaca#172]
**Is your feature request related to a problem? Please describe.**
I am a user of NixOS, on this system you can configure everything in one config file.
My config file has
```nix
  services.ollama = {
    enable = true;
    acceleration = "cuda";
  };
```
and this starts my shared local ollama instance on boot that is then used by every AI interface that needs it, for example: Neovim plugin.

In my opinion ollama was never meant to be bundled with some app and was always meant to be a shared backend.
What you are doing is similar to bundling docker with your app to start it's own microservice based app-backend-docker-compose.yml.
And then dealing with the hassle of running docker in rootless mode.

By relying on the USER to set up ollama on their system you would save yourself the hassle of running ollama under the flatpak sandbox. Then this app will be just a frontend that only needs network permissions to communicate with the ollama server.

**Describe the solution you'd like**
Allow to build the program without the embedded ollama instance, or **stop trying to bundle ollama** entirely.

If you still want to bundle ollama because of some reasons like:
- Target audience doesn't know how to set up ollama on their system (they can ask chatgpt or claude opus)
- Achieving "Questionable User Convenience Ideals" at the cost of "Actual User And Developer Convenience"

Then you probably won't change your mind, so I will just ask for a build option.

**Describe alternatives you've considered**
Setting the remote ollama server to localhost, but it's something that you have to do manually in the UI on first launch and you have a duplicate instance of ollama running.

If you go with it and let alpaca be the main local ollama server, you don't have access to all the models that you already pulled while using your main local ollama instance and copying them to the location where the alpaca ollama instance can see them is a hassle and a giant waste of space. Symlinking models managed by ollama is not an option either in my opinion.

Not to mention that if alpaca is not the only ollama interface you use and you want to use just ollama but don't want to start alpaca gtk app then you are out of luck and you will have to start alpaca to then interface with ollama through neovim or other program.

**Comment by Jeffser** [comment]
The idea of ​​the app is to give an easy way to chat with AI locally for novice users, I could separate Ollama and make it an extension of the app in the same way Gamescope is for Steam on Flathub, but I think this would bring some friction to users who want something that just works by downloading it. Now, if you want to remove Ollama from the Alpaca Flatpak, it is located at `~/.local/share/flatpak/app/com.jeffser.Alpaca/current/active/files/bin/ollama` or `/var/lib/flatpak/app/com.jeffser.Alpaca/current/active/files/bin/ollama` depending on your installation.

For the next version I will include a fallback that prompts the user for a remote connection if that binary file is missing

**Comment by jaredmontoya** [comment]
Thank you!
I knew that

> The idea of ​​the app is to give an easy way to chat with AI locally for novice users

was probably the case but still decided to try my luck because your ollama frontend is SO GOOD that it's far beyond what I would call an app for novice AI users.

**Comment by Jeffser** [comment]
well thank you for that, I appreciate it <3
