### ISSUE TITLE
Allow going into model page from downloaded models

### ISSUE THREAD

**Issue by Yiannis128** [Jeffser/Alpaca#173]
There is no way to access model pages from downloaded models in the Manage Models page.

Allow for a way to access the models page.

**Comment by Jeffser** [comment]
Hi, unfortunately I can't do this because models by themselves don't provide a URL, the list of available models is "hard-coded" into the app whilst the downloaded models are dynamically shown. Long story short, it will be hard and inconsistent so I'm not going to do it, sorry
