### ISSUE TITLE
Option to close/hide the sidebar

### ISSUE THREAD

**Issue by talal** [Jeffser/Alpaca#182]
**Is your feature request related to a problem? Please describe.**

Hi, on small screens the sidebar takes a lot space.

**Describe the solution you'd like**

Kindly add the ability to close/hide the sidebar through a button or keyboard shortcut so that it doesn't take up screen real-estate when not in use.

**Comment by Jeffser** [comment]
Hi, thanks for the suggestion

![image](https://github.com/user-attachments/assets/fc5aa76c-79df-4a97-a7cb-b97ce1c87bb8)

[I just did it](https://github.com/Jeffser/Alpaca/commit/b373b6a34f2c8b448c77a80e40fe272396063fda)

**Comment by talal** [comment]
Thanks for the quick response.

Can you also update the Flatpak release on Flathub?

**Comment by Jeffser** [comment]
yeah sure I will do that later tonight, I'm working on a newish feature for the next version!

**Comment by bragefuglseth** [comment]
Can't this be automated like other GNOME apps do? I don't think there's a need for a manual toggle.

**Comment by Jeffser** [comment]
> Can't this be automated like other GNOME apps do? I don't think there's a need for a manual toggle.

It is automated by default, that's why I removed the button before, if you make the window really small the sidebar closes

**Comment by bragefuglseth** [comment]
Given that OP reported this, though:

> Hi, on small screens the sidebar takes a lot space.

Maybe the collapse threshold should be increased a little? Them having to manually hide the sidebar because it takes too much space is an example what we jokingly call [shit work](https://zachholman.com/posts/shit-work/) :slightly_smiling_face:

**Comment by Jeffser** [comment]
yeah yeah sure I will increase it
