### ISSUE TITLE
Add a popup when update is available

### ISSUE THREAD

**Issue by GaPhilippone** [Jeffser/Alpaca#183]
**Is your feature request related to a problem? Please describe.**
I'm still using 1.0.2 of the app and now it's 1.0.4. Not popup that there is an update in Alpaca.
When using the update software on the os (tested on Ubuntu/Zorin/Debian), there is no info about flatpack having update or not without going to the software library.

**Describe the solution you'd like**
A popup that say there is a new version

**Describe alternatives you've considered**
Always going to github to verify is too much

![Screenshot from 2024-08-03 04-54-33](https://github.com/user-attachments/assets/ad4a6e9b-eaa7-46ed-a6e8-c156c87269df)

![Screenshot from 2024-08-03 04-55-00](https://github.com/user-attachments/assets/ee1e09b9-458b-4766-bbc3-dd56b7d425e2)

![Screenshot from 2024-08-03 04-55-38](https://github.com/user-attachments/assets/8aa84f0c-c584-4c81-a5e0-f122f4266cbe)

PS: wanted to add it to https://github.com/Jeffser/Alpaca/issues/97 but it is locked to collaborators

**Comment by Jeffser** [comment]
Hi, thanks for the suggestion, whilst it is possible, I want Alpaca to use the internet as little as possible, your distribution should notify / auto update Flatpaks, if not you should probably check the preferences in Software Center

![image](https://github.com/user-attachments/assets/67498dd4-179c-4ee3-83ab-ba4b629a5170)

I'm not sure if this is an option on Zorin OS, if not then you should ask them to update the version of Software Center they are shipping or turn on the option for users to change that.

**Comment by GaPhilippone** [comment]
okay thank, on Ubuntu (VM) and Debian (VM) and Zorin (real), there a no option to check flatpak.
Or i'm just blind

**Comment by Jeffser** [comment]
I'm not sure since use Fedora, the option should be here

![image](https://github.com/user-attachments/assets/8e15345f-b644-454b-a1af-f87396e597d0)

Please tell me if it's not there

**Comment by GaPhilippone** [comment]
Ok i have checked. There is an otion to say there is update and to install in background. The pb is that you have no update install if the app is always used.
![Screenshot from 2024-08-03 05-18-23](https://github.com/user-attachments/assets/12954792-edc6-4259-bcd7-b1975974ed2a)
So no updates if the app is always open.

**Comment by Jeffser** [comment]
well that makes sense, I know it is annoying but that's how it gotta be, sorry

**Comment by GaPhilippone** [comment]
No pb, you are doing a great job (for me at least) so i thank you for this. It help me really for my projects
