### ISSUE TITLE
It switch between models sometimes without change by user

### ISSUE THREAD

**Issue by GaPhilippone** [Jeffser/Alpaca#184]
**Describe the bug**
I'm using Deepseek Coder V2 and Llama 3
When generating answers, i choose deepseek and the answer is generated, but in the same channel, when i ask somewthing else, the model change at random to Llama 3 after entering the prompt.
It's a little random, sometime after 3-4 prompts, there is no model change. After 1 (or number random of prompt), it change to Llama 3.

Or when changing channel, it choose Deepseek or llama 3 but i didn't click to change.

Is the model connected to the channel i use ?
Like Channel 1 -> Llama 3 and Channel 2 -> Deepseek

**Expected behavior**
No change in the same channel between models
Or setup a model for each channel i don't know

**Screenshots**
![Screenshot from 2024-08-03 05-08-47](https://github.com/user-attachments/assets/eba812b9-a114-4910-9a78-263f63448257)
![Screenshot from 2024-08-03 05-09-05](https://github.com/user-attachments/assets/f3e6a828-191f-49bf-889c-515089d6c19b)

Edit: i will check with 1.0.4

**Comment by Jeffser** [comment]
Hi thanks for mentioning this, [this](https://github.com/Jeffser/Alpaca/commit/003d6a3d5fb6f8e395774d83c8392f9e2008ee86) should fix it.

How it works is that it reselects the last model used on the chat when the app is launched or the user changes the chat.

If this doesn't work on 1.0.5 (should be out in a couple of hours) please reopen the issue, thanks!
