### ISSUE TITLE
Restart/continue generate answer

### ISSUE THREAD

**Issue by GaPhilippone** [Jeffser/Alpaca#185]
**Is your feature request related to a problem? Please describe.**
When starting the app or after some time (Ollama instance server went down (keepalive expired) and restart / reset), sometime the answer will stop generate so i need to copy/paste what i asked so that the answer will be generated

**Describe the solution you'd like**
A button to resend the prompt when ollama have been reset/restart to regenerate the answer after the ollama_server is restarted.

**Describe alternatives you've considered**
Copy/Paste of prompt is still working

**Additional context**
In vscodium with extension "Continue" for working with IA, you can click a button to restart/continue the generation if it stopped when generating the answer if this example can help to describe.

In the screenshot, you see it say it's generating but only after copy/paste of my prompt after a ollama server reset
![Screenshot from 2024-08-03 05-30-32](https://github.com/user-attachments/assets/c1b6d2b0-48d6-4468-a55d-543f0f80f9ef)

**Comment by Jeffser** [comment]
This is a great idea actually, I will try to add a regen button when the response gets interrupted, thanks!

**Comment by GaPhilippone** [comment]
Yes i think so. Just now stopped generating. ollama_server in task disappeared and Alpaca saying it still doing it:
![Screenshot from 2024-08-03 06-17-38](https://github.com/user-attachments/assets/17587f90-f7b6-4d4f-ba3a-617eed132be7)

So i need to restart the prompt by copy/paste and delete the chat to have it cleaned

**Comment by Jeffser** [comment]
Hi so I just added this, when the response fails this button appears

![image](https://github.com/user-attachments/assets/3596afed-7b7a-483c-8c3d-10f300836b0d)

Even if the response works now the user can regenerate any response, it doesn't matter if it is the latest message or not

![image](https://github.com/user-attachments/assets/ece5983e-161e-41c5-9c18-5c7d57bc3b3d)

https://github.com/Jeffser/Alpaca/commit/0d1b15aafcf2ca805c7cc8291ca4b08756cda03b
