### ISSUE TITLE
stop in middle of generating answer

### ISSUE THREAD

**Issue by GaPhilippone** [Jeffser/Alpaca#186]
**Describe the bug**
When generating, no error message or reset message.
Just ollama_server stopped and disappear from the task manager.
Tested 3 times, 5 min after it happen

**Expected behavior**
Finish generating answer

**Screenshots**
Prompt sent:
![Screenshot from 2024-08-03 06-29-53](https://github.com/user-attachments/assets/774b9455-4e42-4776-ad7d-6ce7c035f59d)

Bug:
![Screenshot from 2024-08-03 06-36-06](https://github.com/user-attachments/assets/41aa1a94-ae39-4699-8d86-1da0a9be3ab3)

**Additional context**
No idea what's happening or if there is some logs somewhere i can send.
Will try by launching with flatpak in cli

PS: reposted the comment in this issue since it was linked and not needed in the enhancement

Yes i think so. Just now stopped generating. ollama_server in task disappeared and Alpaca saying it still doing it:
![Screenshot from 2024-08-03 06-17-38](https://github.com/user-attachments/assets/17587f90-f7b6-4d4f-ba3a-617eed132be7)

So i need to restart the prompt by copy/paste and delete the chat to have it cleaned

PS: i was preparing a coffee when it happened

**Comment by GaPhilippone** [comment]
`INFO	[window.py | show_notification] ```Titre Template Et Structure Jeu Rts Multijoueur...,  Bien sûr ! Voici un template pour votre projet multijoueur de type RTS avec une interface utilisate...
[GIN] 2024/08/03 - 06:47:38 | 200 | 36.346576882s |       127.0.0.1 | POST     "/api/generate"
INFO	[window.py | rename_chat] Renaming chat "New Chat" -> "```Rts Game Platform Avec Crud, Tableau De Bord Et..."
[GIN] 2024/08/03 - 06:51:47 | 200 |         4m45s |       127.0.0.1 | POST     "/api/chat"
Exception in thread Thread-3 (run_message):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/share/Alpaca/alpaca/window.py", line 984, in run_message
    response = connection_handler.stream_post(f"{connection_handler.url}/api/chat", data=json.dumps({"model": model, "messages": messages}), callback=lambda data, id=id: self.update_bot_message(data, id))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/Alpaca/alpaca/connection_handler.py", line 29, in stream_post
    callback(json.loads(line.decode("utf-8")))
  File "/app/share/Alpaca/alpaca/window.py", line 984, in <lambda>
    response = connection_handler.stream_post(f"{connection_handler.url}/api/chat", data=json.dumps({"model": model, "messages": messages}), callback=lambda data, id=id: self.update_bot_message(data, id))
                                                                                                                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/Alpaca/alpaca/window.py", line 951, in update_bot_message
    if data['done']:
       ~~~~^^^^^^^^
KeyError: 'done'

`

Got this in CLI

**Comment by GaPhilippone** [comment]
Can it be because of the title generated with so many ''''XXXXX''''

**Comment by GaPhilippone** [comment]
It seem the problem is not happening with Llama 3.1 and the title don't have ''''''' and the answer is generated but the code is not formatted correctly:
![image](https://github.com/user-attachments/assets/7249c598-fb28-4256-90f5-53a9c39d475a)

**Comment by Jeffser** [comment]
I can't do anything about models throwing random '''''' I hate that it happens but that's the price I pay for making an app that works on any model that does whatever they want to do

**Comment by GaPhilippone** [comment]
oh okay. just wondering if it was the pb

**Comment by Jeffser** [comment]
This should stop that particular error

https://github.com/Jeffser/Alpaca/commit/72063a15d9db28a1d69a36608399ee1514172934

I'm not sure why Ollama isn't outputing the 'done' key but this should catch that

**Comment by GaPhilippone** [comment]
thank you. I will wait for the update.
For a dev like you, it would seem funny i'm trying to generate a game with AI but i'm a noob in dev.
"Got idea but no petroleum" XDD

**Comment by GaPhilippone** [comment]
> This should stop that particular error
> 
> [72063a1](https://github.com/Jeffser/Alpaca/commit/72063a15d9db28a1d69a36608399ee1514172934)
> 
> I'm not sure why Ollama isn't outputing the 'done' key but this should catch that

Wait, the answer was not finished generating so ollama can't output "done". The ollama_server stopped when generating in the middle of it, not after it was done, so not sure if the code will work. 
Maybe i just explained badly  the issue

**Comment by Jeffser** [comment]
well I mean if the server shuts down the whole function should just stop, if it persists on the next version please tell me

**Comment by Jeffser** [comment]
> thank you. I will wait for the update. For a dev like you, it would seem funny i'm trying to generate a game with AI but i'm a noob in dev. "Got idea but no petroleum" XDD

Do you have something on mind?

**Comment by GaPhilippone** [comment]
> well I mean if the server shuts down the whole function should just stop, if it persists on the next version please tell me

Oh okay, will do.

**Comment by GaPhilippone** [comment]
> > thank you. I will wait for the update. For a dev like you, it would seem funny i'm trying to generate a game with AI but i'm a noob in dev. "Got idea but no petroleum" XDD
> 
> Do you have something on mind?

Yeah, i have 3 ideas in the work. 
First is a game to have starting fund to build idea 2. It need html5, css3, mysql, php et threejs for it.

Second is an IT infrastructure for hosting with reduce cost (like it cut 90% of infra cost in my tests) so cost for customer is really reduced and money will be reinvested in idea 3. It need html5, css3, mysql, php for frontend and the backend i tested it and it work.

Idea 3 is to use the money generated in 1, 2 to reinvest in open source for developpers to let them give fly to theirs ideas and use Idea 2 to host their projects.

**Comment by Jeffser** [comment]
Soooo like a tycoon?

**Comment by Jeffser** [comment]
I mean like what would be the gameplay exactly? I have some experience with game development, not a lot but some

**Comment by GaPhilippone** [comment]
> Soooo like a tycoon?
Not my goal to be a tycoon.
I just want to reduce IT (like datacenter, infrastructure, proprietary software etc) impact on the planet and users.
How much cooling/electricity is needed for IT is too much really.
Developpers of open source are too much badly mentionned and despised in companies i have worked for in my 10 years of exp

**Comment by Jeffser** [comment]
nono, there's a type of game called tycoon, that's what I meant

**Comment by GaPhilippone** [comment]
> I mean like what would be the gameplay exactly? I have some experience with game development, not a lot but some

The game i see for V1 is much like a crossover of management of ressources, military and strategy.
There was a game i played in a broswer but the call of money destroyed the balance and so many players left because of it.

**Comment by Jeffser** [comment]
> > I mean like what would be the gameplay exactly? I have some experience with game development, not a lot but some
> 
> The game i see for V1 is much like a crossover of management of ressources, military and strategy. There was a game i played in a broswer but the call of money destroyed the balance and so many players left because of it.

So a tycoon

**Comment by Jeffser** [comment]
you know what? it's really late I'm going to go sleep after I release the 1.0.5 version of Alpaca on Flathub, please just make a list of stuff you want to see on the game and I will consider it tomorrow

**Comment by GaPhilippone** [comment]
> tycoon

ah yeah tycoon like in city builder you mean. there is some similarity, yes, like 20%

**Comment by GaPhilippone** [comment]
> you know what? it's really late I'm going to go sleep after I release the 1.0.5 version of Alpaca on Flathub, please just make a list of stuff you want to see on the game and I will consider it tomorrow

okay but maybe it's better if we don't speak in Alpaca repository of this no ?

**Comment by Jeffser** [comment]
my user in discord is the same as GitHub, you can DM me if you want to

**Comment by GaPhilippone** [comment]
> my user in discord is the same as GitHub, you can DM me if you want to

will do thanks

**Comment by GaPhilippone** [comment]
> I can't do anything about models throwing random '''''' I hate that it happens but that's the price I pay for making an app that works on any model that does whatever they want to do

ahaha sorry but title in russian when prompt is english is so funny:
![Screenshot from 2024-08-03 21-21-49](https://github.com/user-attachments/assets/314e4897-64c3-45b7-93d7-4695d3132e33)
