### ISSUE TITLE
Japanese input method not working

### ISSUE THREAD

**Issue by nannoda** [Jeffser/Alpaca#193]
**Describe the bug**
I am unable to confirm my input after press enter key. For some reason it stuck at the selecting stage. The only way to exit that state is for me to change my input method to English or click somewhere else, which is less than ideal.
I am currently running with the following configuration:
System: Fedora Linux 40
IME: Mozc
DE: GNOME 46.3.1 

**Expected behavior**
I was expecting to be able to select and enter as normal text boxes.

**Screenshots**
I am unable to provide a screenshot.

**Additional context**
The dropdown menu appears in a random place that is not common for normal text boxes.

**Comment by Jeffser** [comment]
Hi, thanks for the report, I will test this on my installation and see what I can do

**Comment by Jeffser** [comment]
I'm able to write in japanese fine, could you send me a video?

**Comment by Jeffser** [comment]
My bad I dind’t realize I use Anthy instead of Mozc．I see your problem now, I'm going to work on it

**Comment by Jeffser** [comment]
The fix is ready! thanks for the report

https://github.com/Jeffser/Alpaca/commit/60351d629d18bed9486fa923358fcd81b17743ef
