### ISSUE TITLE
Make internal ollama instance listen on different IP to avoid conflicts

### ISSUE THREAD

**Issue by Darin755** [Jeffser/Alpaca#199]
**Is your feature request related to a problem? Please describe.**
Right now the internal ollama I stance listens on 127.0.0.1. This is problematic as it conflicts with other instances and potentially other services on that port. 

**Describe the solution you'd like**

Ideally the internal ollama instance should listen on a random internal IP. The 127.0.0.1/8 subnet has 16 million IP addresses so there is plenty of room.

A similar solution can be found in systemd resolved. It listens on 127.0.0.53:53 so that it won't conflict with anything on the host.

**Describe alternatives you've considered**
You also could make it listen on a random port. I don't think this is as good of an answer though as there is a higher chance of a port conflict.

**Comment by Jeffser** [comment]
Hi, thanks for the suggestion I will look into it

The app right now uses the port `11435` Ollama by default would use `11434` so it doesn't interfere with it

**Comment by Darin755** [comment]
In that case the issue is flatpak. Thanks
