### ISSUE TITLE
Automatically scroll

### ISSUE THREAD

**Issue by imbev** [Jeffser/Alpaca#2]
I suggest the following:

If the user is currently scrolled to the bottom, the scroll should remain at the bottom despite new responses.

**Comment by Jeffser** [comment]
Sounds good, will work on it tomorrow

**Comment by Jeffser** [comment]
[Done](https://github.com/Jeffser/Alpaca/commit/d989ec5324c40f43b60731294c6a3b48a8258d92)

Thank you for the suggestion!
