### ISSUE TITLE
make an option for external model

### ISSUE THREAD

**Issue by olumolu** [Jeffser/Alpaca#201]
officially at the point of time ollama does not support uncensored llama 3 or 3.1 at the point of time some one provide this using ollama
Example
`ollama pull rjmalagon/dolphin-2.9.4-llama3.1-8b:q8_0`
some maybe available in as gguf from hugging face.
If those can also be install just like the commend like ollama can.
This can be implemented with manually install those models can import the tag with alpaca maybe alpaca can run 
`Ollama list` to get the new unofficial models to be list them down from gui with alpaca provide official and unofficial model support is complicated at least i can imagine how this can be implemented fully from the gui app.
Is it possible to integrate this feature.

**Comment by Jeffser** [comment]
welp good news Alpaca supports gguf

I will add support to pull just with the name from external repos

**Comment by Jeffser** [comment]
[It's done](https://github.com/Jeffser/Alpaca/commit/3c553e37d884f911daa571eefd2e488b406e5cd8), thanks for the suggestion

Tested with: `rjmalagon/dolphin-2.9.4-llama3.1-8b:q8_0`

![image](https://github.com/user-attachments/assets/8a7274ae-bac9-41d2-8fd2-05e577d7cb88)

**Comment by olumolu** [comment]
> [It's done](https://github.com/Jeffser/Alpaca/commit/3c553e37d884f911daa571eefd2e488b406e5cd8), thanks for the suggestion
> 
> Tested with: `rjmalagon/dolphin-2.9.4-llama3.1-8b:q8_0`
> 
> ![image](https://private-user-images.githubusercontent.com/69224322/356050602-8a7274ae-bac9-41d2-8fd2-05e577d7cb88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODUzMTIsIm5iZiI6MTcyMzA4NTAxMiwicGF0aCI6Ii82OTIyNDMyMi8zNTYwNTA2MDItOGE3Mjc0YWUtYmFjOS00MWQyLThmZDItMDVlNTc3ZDdjYjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDAyNDMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2MDEyOGE2Y2U1M2U3ZjliNWIzMmIzNDMyOGJmZDc5Yzg1ZThmOGFmYjVjNDk3NjY1NDI0Mjk0MWVjZjdjODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HnxNnMqYFEP9RmxFCl2cQVJXN26ykXdUgc5CivikTBA)

That is too fast

**Comment by geckolinux** [comment]
Thanks for this improvement! By any chance will it work with HuggingFace GGUF models? For example I can do this with Ollama to pull it from HuggingFace:
`ollama run hf.co/lmstudio-community/Mistral-Small-24B-Instruct-2501-GGUF:Q8`

**Comment by Jeffser** [comment]
> Thanks for this improvement! By any chance will it work with HuggingFace GGUF models? For example I can do this with Ollama to pull it from HuggingFace: `ollama run hf.co/lmstudio-community/Mistral-Small-24B-Instruct-2501-GGUF:Q8`

You can use the option at the top right corner of the model manager to pull models by name and just input that name there, it worked for me by replacing `Q8` with `latest`

**Comment by geckolinux** [comment]
Very cool, well done @Jeffser !
