### ISSUE TITLE
Add a log of ollama crash output to UI

### ISSUE THREAD

**Issue by Cyborgscode** [Jeffser/Alpaca#202]
**Is your feature request related to a problem? Please describe.**

Yes, Ollama is dying after a lot of images related api connections

Also i noticed read timeouts on the ollama api for some requests,
so some stats in the log would help.

**Describe the solution you'd like**

We need a log window/tab to check why it died, when it died.

**Comment by Jeffser** [comment]
Hi there's a log of Alpaca available on 'About Alpaca' > Troubleshooting > Debugging Information

I just added Ollama's output to that dialog
