### ISSUE TITLE
Remove background card

### ISSUE THREAD

**Issue by TylerLaBree** [Jeffser/Alpaca#21]
Currently, sent input text is placed in a card, which is placed in another card which contains the chat, which is placed on the background.

![image](https://github.com/Jeffser/Alpaca/assets/51167014/f7f9e86c-23a2-41ac-9a25-77a618fd0a91)

Consider removing this "whole chat" card, and instead place the output text directly on the background.

This design is shared by occasional descriptive text in gnome settings (below) and in the layout of [chatgpt.com](chatgpt.com)

![image](https://github.com/Jeffser/Alpaca/assets/51167014/0febe112-9150-4d7a-8c98-c93e57ae0f1b)

**Comment by Jeffser** [comment]
![image](https://github.com/Jeffser/Alpaca/assets/69224322/1de88dd8-79fd-4ec9-9297-fc72387ce250)

Hi thanks for the feedback, you mean something like [this](https://github.com/Jeffser/Alpaca/commit/d7987fa4a5abbc1342248310998401727b34201c)?

**Comment by TylerLaBree** [comment]
That looks great! It could also mimic the chatgpt/text message layout, of having the input message on the right half of the screen, but that's a more complicated change.

![image](https://github.com/Jeffser/Alpaca/assets/51167014/b585f994-6b53-41e0-a2e8-45039ed43967)

**Comment by Jeffser** [comment]
I'm not sure how to do that honestly, GTK is kinda stiff about setting the size of widgets

**Comment by TylerLaBree** [comment]
> I'm not sure how to do that honestly, GTK is kinda stiff about setting the size of widgets

I know very, _very_ little about this, but I've found where Flare did something similar:

https://gitlab.com/schmiddi-on-mobile/flare/-/blob/master/data/resources/ui/message_item.blp#L92

It looks like a custom widget(?)

I've also never made a gtk app, but I'm interested in learning. If I have time, I might try to help out in understanding stuff like this a bit more.

**Comment by Jeffser** [comment]
I also don't know a lot, this is the first time I use GTK so there's a lot I don't know, I'm pretty sure that's a grid, those should not be used in stuff like that as far as I know.  What I could do is justify the text to the right side of the screen

**Comment by TylerLaBree** [comment]
Sure! Thanks, I appreciate it!

**Comment by TylerLaBree** [comment]
I think this can be closed, since the background card is now gone.
