### ISSUE TITLE
blank space under bubble on startup

### ISSUE THREAD

**Issue by loulou64490** [Jeffser/Alpaca#213]
**Describe the bug**
there is a blank space on startup under chat bubble, but disappear at scroll start

**Expected behavior**
no blank space lol

**Screenshots**
![Capture d’écran du 2024-08-10 17-27-19](https://github.com/user-attachments/assets/2c9231ed-0cfe-4e9b-bbcb-4244d0b9a7dd)

**Additional context**
no, still not

**Comment by Jeffser** [comment]
GTK does that sometimes, I'm not sure why, scrolling fixes it (even when you can't actually scroll)
