### ISSUE TITLE
Chat duplication

### ISSUE THREAD

**Issue by loulou64490** [Jeffser/Alpaca#214]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
a button in the chat submenu to "duplicate"

**Describe alternatives you've considered**
there isn't 

**Additional context**
no, never additional context

**Comment by Jeffser** [comment]
[Done](https://github.com/Jeffser/Alpaca/commit/b8fe222052dd2ef74afc5d441f26f076ebd7a57b)

Thanks for the suggestion
