### ISSUE TITLE
bad language diplayed

### ISSUE THREAD

**Issue by loulou64490** [Jeffser/Alpaca#215]
**Describe the bug**
alpaca display python2 whereas it's python3 and the model only specify python

**Expected behavior**
Just display Python like the model indicate, or detect python3

**Screenshots**
![Capture d’écran du 2024-08-10 17-49-23](https://github.com/user-attachments/assets/4d90762e-78d2-463a-9a54-d230bb49b72c)

**Additional context**
no, never more context I say

**Comment by Jeffser** [comment]
The models normally provide a coding language, most of them just say python and that widget defaults to python2, what I'm going to do is replace 'python' with 'python3' every time the model wants to make a code block

**Comment by Jeffser** [comment]
[Fixed](https://github.com/Jeffser/Alpaca/commit/f2b243cd5ff38b31d33746ff82d3dbf14cbcb44c)

thanks for the report
