### ISSUE TITLE
custom title replaced by auogenerated

### ISSUE THREAD

**Issue by loulou64490** [Jeffser/Alpaca#216]
**Describe the bug**
When I write a custom title to a chat then I send the first message, the title is replaced, and that's make me sad

**Expected behavior**
When you write a custom title, you don't generate one

**Screenshots**
[Capture vidéo du 2024-08-10 18-01-32.webm](https://github.com/user-attachments/assets/18a3e32b-60eb-4b7c-a79a-71cfbd4ebb10)

**Additional context**
qzkjdhqskflqpizkhebq

**Comment by Jeffser** [comment]
[Fixed](https://github.com/Jeffser/Alpaca/commit/47f5c88ef2107abb0339afc344721250a406269c)

Thanks for the report
