### ISSUE TITLE
can't export chat

### ISSUE THREAD

**Issue by loulou64490** [Jeffser/Alpaca#218]
**Describe the bug**
when I try to export chat, the save pop-up appear and then.... nothing

**Expected behavior**
Alpaca generate the export

**Screenshots**
[Capture vidéo du 2024-08-10 18-39-05.webm](https://github.com/user-attachments/assets/4edc39c3-eccc-4f24-9d61-abcd241e369c)

**Additional context**
😳

**Comment by Jeffser** [comment]
[Fixed](https://github.com/Jeffser/Alpaca/commit/404d4476aed01f4a3372516d05775da9af470b1e)

thanks for the report
