### ISSUE TITLE
impossible to send message after clearing the chat

### ISSUE THREAD

**Issue by loulou64490** [Jeffser/Alpaca#219]
**Describe the bug**
when I clear the chat, I can't send anymore message

**Expected behavior**
send new message

**Screenshots**
[Capture vidéo du 2024-08-10 18-44-42.webm](https://github.com/user-attachments/assets/06526496-ce7e-41c7-aece-3351080df683)

**Additional context**
🥵🥵🥵🥵🥵

**Comment by Jeffser** [comment]
clearing the chat actually corrupted the save data because it was using the structure I used when I first added multiple chats, thanks for reporting it

https://github.com/Jeffser/Alpaca/commit/a66c6d5f40dd461097ec427fa6bbae0c7592baca
