### ISSUE TITLE
Left sidebar spacing / removal of inactive cards

### ISSUE THREAD

**Issue by TylerLaBree** [Jeffser/Alpaca#22]
The current layout of the left sidebar is shown below.

![image](https://github.com/Jeffser/Alpaca/assets/51167014/d68883b7-8e34-4ebb-b97e-38eb485a89d4)

Consider placing the inactive chat text directly on the left sidebar background, as seen in Fractal, below. It could also be good to decrease vertical spacing between chat names. Spacing is good for visibility, but right now Alpaca has more than gnome settings or Fractal.

![image](https://github.com/Jeffser/Alpaca/assets/51167014/08a33648-6319-494a-a569-433f115cc186)

In addition, it could be nice to hide "delete" and "rename" icons behind a "three-dots" button or put them in a right click drop-down menu.

**Comment by Jeffser** [comment]
Thanks for the feedback, I will work on this

**Comment by Jeffser** [comment]
what about this? what do you think about the gray background on the active chat? should I change it?

![image](https://github.com/Jeffser/Alpaca/assets/69224322/a3ec8471-331c-43e4-857c-be17042319cd)

**Comment by Jeffser** [comment]
[Screencast from 2024-05-22 14-23-42.webm](https://github.com/Jeffser/Alpaca/assets/69224322/886a873c-de67-4a0c-92e0-13c9f1a2abd5)

**Comment by TylerLaBree** [comment]
The color looks great!

I'd also recommend reducing by about 20% the vertical size of the entries. You can do this by reducing the entry button height and the spacing between buttons. Alpaca fits four entries in the same space where gnome settings fits five.

![image](https://github.com/Jeffser/Alpaca/assets/51167014/0b30aa9a-9d03-4490-bda7-4d8c631fc892)

**Comment by TylerLaBree** [comment]
Looks great!

**Comment by Jeffser** [comment]
![image](https://github.com/Jeffser/Alpaca/assets/69224322/0b1eb4a7-d351-4bff-b759-04646c4486fe)

I don't get how context menus work so that's how it's for now

**Comment by Jeffser** [comment]
Btw what do you think of the text 'Chats' should I remove it?

**Comment by Jeffser** [comment]
I just did something cool
[Screencast from 2024-05-22 19-45-28.webm](https://github.com/Jeffser/Alpaca/assets/69224322/6ef42188-6315-4adf-b013-a07ac137cad3)

**Comment by TylerLaBree** [comment]
> Btw what do you think of the text 'Chats' should I remove it?

It's great and it's not. I love the look, but it sort of gives me the impression that the app is named "Chats", instead of being a sidebar label.

Tuba has it's app title centered on the top of the left sidebar:

![image](https://github.com/Jeffser/Alpaca/assets/51167014/4903e883-106e-404a-bd74-b2696a963627)

Foliate does the same, and labels its sections with a smaller font

![image](https://github.com/Jeffser/Alpaca/assets/51167014/7342b84a-2569-4da0-8e5d-cfc88d1a48ee)

ChatGPT opts for no sidebar title since it's a website, and labels sections based on how recently you've interacted with the chats.

![image](https://github.com/Jeffser/Alpaca/assets/51167014/182a5ab0-ad29-4ba5-a086-49d43f6ea465)

All this is to say that the label "Chats" might tell the user something that they already would assume. Maybe it could be changed to a smaller "Alpaca" centered on the sidebar?

Aside: There's also a really cool "new chat icon" used by Flare.

![image](https://github.com/Jeffser/Alpaca/assets/51167014/9d6e6d08-0408-402a-812c-ea64c16efa5c)

**Comment by TylerLaBree** [comment]
> I just did something cool [Screencast from 2024-05-22 19-45-28.webm](https://github.com/Jeffser/Alpaca/assets/69224322/6ef42188-6315-4adf-b013-a07ac137cad3)

That looks great! Similar to ChatGPT

https://github.com/Jeffser/Alpaca/assets/51167014/7498dafd-3870-4a84-be05-58c51351ff29

**Comment by Jeffser** [comment]
I might try the Flare thing it looks great

**Comment by TylerLaBree** [comment]
Awesome! To clarify by the way, in light mode the font is dark, not light gray. The other screenshots were when the window was not focused.

![image](https://github.com/Jeffser/Alpaca/assets/51167014/6e940462-b048-4d89-bbb3-a806c0b40abc)

![image](https://github.com/Jeffser/Alpaca/assets/51167014/acecdff7-1a8c-47be-9aeb-6f62f4fd9591)

**Comment by Jeffser** [comment]
I'd say this is enough, thanks for you all for the help

https://github.com/Jeffser/Alpaca/pull/35

![image](https://github.com/Jeffser/Alpaca/assets/69224322/8c3c08c1-f5f3-4272-ae76-f1fded184e9b)
