### ISSUE TITLE
Stop generating button doesn't reset

### ISSUE THREAD

**Issue by loulou64490** [Jeffser/Alpaca#220]
**Describe the bug**
When I stop the generation, the button remains red like if it was generating something

**Expected behavior**
the button become blue

**Screenshots**
[Capture vidéo du 2024-08-10 18-50-46.webm](https://github.com/user-attachments/assets/f8568f8b-eab8-4386-8339-83b5090d00fe)

**Additional context**
I don't think so...

**Comment by Jeffser** [comment]
bruh but it became blue on the video

**Comment by loulou64490** [comment]
it become blue when I click again

**Comment by Jeffser** [comment]
could you check if this still happens for you on the newest version please?

**Comment by loulou64490** [comment]
[Capture vidéo du 2024-08-11 07-34-59.webm](https://github.com/user-attachments/assets/280ae4c3-2424-49c3-9ae5-aaf0e9d06ad8)
the button itself doesn't reset, and you have to click again

**Comment by Jeffser** [comment]
could you give me the logging information? it should be on: primary menu > about Alpaca > troubleshooting > debugging information

**Comment by Jeffser** [comment]
or just run alpaca from a terminal `flatpak run com.jeffser.Alpaca`

**Comment by loulou64490** [comment]
I don't have my PC now, but I had looked and there was any error or special message
