### ISSUE TITLE
model and date not saved when generation stopped

### ISSUE THREAD

**Issue by loulou64490** [Jeffser/Alpaca#221]
**Describe the bug**
when I stop the generation, the model and the date aren't savec and displayed in the chat

**Expected behavior**
maybe save them anyway

**Screenshots**
![Capture d’écran du 2024-08-10 18-55-29](https://github.com/user-attachments/assets/dc490d42-2af3-4658-b24f-c6cbe1fd8d00)

**Additional context**
NO NO AND NOOOOO

**Comment by Jeffser** [comment]
the date was always saved but it wasn't shown, I [fixed it](https://github.com/Jeffser/Alpaca/commit/33b7cae24d9e6c0098d6f14589862e28ab2179c5), thanks for the report
