### ISSUE TITLE
message disappear after regeneration

### ISSUE THREAD

**Issue by loulou64490** [Jeffser/Alpaca#222]
**Describe the bug**
when I regenerate a answer, when the generation end, the message disappear and the button are buggy, that's just a display issue because when you change chat et return, the bug is no more present

**Expected behavior**
the regenerated message display normally

**Screenshots**
[Capture vidéo du 2024-08-10 19-13-55.webm](https://github.com/user-attachments/assets/51cd571e-54ba-4a1a-8e31-963838d1917d)

**Additional context**
excuse my english on all issue before, I'm really not fluent and I don't use translator

**Comment by Jeffser** [comment]
Hi thanks for the report,

[fixed](https://github.com/Jeffser/Alpaca/commit/919f71ee78119ba41c00edb66ab96f0adb976901)
