### ISSUE TITLE
Ctrl+Q does not quit ollama process

### ISSUE THREAD

**Issue by laniakea64** [Jeffser/Alpaca#227]
**Describe the bug**
When quitting Alpaca with Ctrl+Q, the `ollama` process that Alpaca started is left continuing to run.

To have quitting Alpaca also quit the `ollama` process, Alpaca must be closed by clicking the "x" button of the window.

**Expected behavior**
Both Ctrl+Q and clicking the "x" should quit the `ollama` process.

**Screenshots**
n/a

**Additional context**
Using latest version of Alpaca installed from Flathub.  OS is Xubuntu 22.04 with `flatpak` version 1.14.8.

**Comment by Jeffser** [comment]
Hi, thanks for the report, I just [fixed it](https://github.com/Jeffser/Alpaca/commit/fd92a86c5eaacd5c178c667026c6ea4484aabba0)
