### ISSUE TITLE
remove subtitle in pop-up

### ISSUE THREAD

**Issue by loulou64490** [Jeffser/Alpaca#228]
Hello, can you remove the subtitle on all pop-up ?
They don't bring anything more, thanks

(here you remove "Renommer")
![Capture d’écran du 2024-08-11 22-01-42](https://github.com/user-attachments/assets/61d4e148-9305-4c71-863d-baf779c612ba)

**Comment by Jeffser** [comment]
I believe your translation is missing '{}'

![image](https://github.com/user-attachments/assets/db3fd2ee-c1dd-4a6c-a50f-d3f2b513e817)

**Comment by loulou64490** [comment]
lol maybe I wil verify
