### ISSUE TITLE
message button dosen't appear when stopping generation

### ISSUE THREAD

**Issue by loulou64490** [Jeffser/Alpaca#229]
[Capture vidéo du 2024-08-11 22-13-09.webm](https://github.com/user-attachments/assets/3d77f799-7a9f-41be-b7c6-ce8476c0fa4f)

**Comment by Jeffser** [comment]
[Fixed](https://github.com/Jeffser/Alpaca/commit/d95f06a2304a6029e392a239399bbf2254c94d7b)

Thanks for the report
