### ISSUE TITLE
Chat history doesn't stay at bottom when sending new input

### ISSUE THREAD

**Issue by TylerLaBree** [Jeffser/Alpaca#23]
The most recent part of the conversation is hidden below the bottom of the screen, unless you scroll down to see it.

**Comment by Jeffser** [comment]
What you are saying is that the chat window should scroll down to the bottom if the user sends a message?

**Comment by TylerLaBree** [comment]
Yep, that's right! I'm not sure if this is easy to implement, but it would be useful.

**Comment by Jeffser** [comment]
It shouldn't be hard, give me a second

**Comment by Jeffser** [comment]
Update: it is hard :D

**Comment by Jeffser** [comment]
What happens is that the widget scrolls to the bottom of the last **bot** response, for some reason it doesn't update the height of the history until the bot starts talking, THEN it does scroll all the way to the bottom.

**Comment by Jeffser** [comment]
Alright, the chat now scrolls down once a message is being received, this is not ideal but it is apparently the only way this works for some reason

**Comment by darkguset** [comment]
Same here, Alpaca v7.6.0 on Linux Mint (Flatpak) and I have to manually scroll to the bottom to see the response.
