### ISSUE TITLE
welcome screen doesn't appear after chat clearing

### ISSUE THREAD

**Issue by loulou64490** [Jeffser/Alpaca#230]
[Capture vidéo du 2024-08-11 22-14-37.webm](https://github.com/user-attachments/assets/550c87d4-5da0-4663-b6c3-746f11157a1d)

**Comment by Jeffser** [comment]
[Fixed](https://github.com/Jeffser/Alpaca/commit/175cfad81c14ef230b8863a65de0892ec4345d65)

Thanks for the report
