### ISSUE TITLE
chat importing doesn't work

### ISSUE THREAD

**Issue by loulou64490** [Jeffser/Alpaca#231]
[Capture vidéo du 2024-08-11 22-17-52.webm](https://github.com/user-attachments/assets/7cf98036-3149-44e0-907f-1162db233c4c)

**Comment by Jeffser** [comment]
[Fixed](https://github.com/Jeffser/Alpaca/commit/938ace91c1f280f34760e78c70816365c31e8567)

Thanks for the report
