### ISSUE TITLE
maybe disable edit and delete button when generating

### ISSUE THREAD

**Issue by loulou64490** [Jeffser/Alpaca#232]
[Capture vidéo du 2024-08-11 22-24-00.webm](https://github.com/user-attachments/assets/7d4ff855-0127-4537-ac45-02f7b33628cc)
[Capture vidéo du 2024-08-11 22-28-34.webm](https://github.com/user-attachments/assets/e4991749-0da6-448f-910e-3f7e9e24c57e)

**Comment by Jeffser** [comment]
I don't see why we should disable them, they don't interfere with the message being generated
