### ISSUE TITLE
maybe create when there is none and a mesage is sent

### ISSUE THREAD

**Issue by loulou64490** [Jeffser/Alpaca#233]
[Capture vidéo du 2024-08-11 22-26-16.webm](https://github.com/user-attachments/assets/4ad1cb4f-37d9-4238-8267-c7c6f6a6dbbc)

**Comment by Jeffser** [comment]
I don't know how you manage to get yourself into that, it should always have at least one chat

**Comment by loulou64490** [comment]
![giphy](https://github.com/user-attachments/assets/3ba31a1a-57c0-4424-b821-7cee9dae3f4c)

**Comment by loulou64490** [comment]
> I don't know how you manage to get yourself into that, it should always have at least one chat

If you delete all chat, there in no more chat, no?
