### ISSUE TITLE
maybe display welcome screen when deleting the last chat

### ISSUE THREAD

**Issue by loulou64490** [Jeffser/Alpaca#234]
[Capture vidéo du 2024-08-11 22-30-48.webm](https://github.com/user-attachments/assets/42cfb24f-66bb-4308-99bd-bdb48391ce29)

**Comment by Jeffser** [comment]
when deleting the last chat a new one should be created automatically, I'm not sure why that doesn't happen to you, I also ran the app in french and it seems like that isn't the problem

**Comment by loulou64490** [comment]
how okay I understand

**Comment by Jeffser** [comment]
I know exactly why that is, your chat file must have all the chats you tried to import before, please delete the whole `~/.var/app/com.jeffser.Alpaca/data/chats` directory

**Comment by loulou64490** [comment]
hooooo yes it works !!!!!!
