### ISSUE TITLE
Previously made models and chats aren't present

### ISSUE THREAD

**Issue by TylerLaBree** [Jeffser/Alpaca#24]
Sometimes, on a fresh start of the app, my previously downloaded models and chats aren't present. When I reboot the app, they come back. Sometimes it takes more than one reboot to fix.

**Comment by Jeffser** [comment]
It's probably that the Ollama instance isn't starting properly, I'm going to rewrite the startup sequence for the instance, maybe that will fix it

**Comment by Jeffser** [comment]
I think the rewrite of that thing should have fixed it, that change it's going to get release on 0.7.0, if you still see the issue then please reopen the issue
