### ISSUE TITLE
display message button only on hover

### ISSUE THREAD

**Issue by loulou64490** [Jeffser/Alpaca#242]
![Capture d’écran du 2024-08-13 17-35-28](https://github.com/user-attachments/assets/a04b9eed-ebad-4606-a4cc-c77b659bed6d)
it's too much
(llama3.1 is so human, I'm really impressed)

**Comment by Jeffser** [comment]
Can't do that, Gnome's Human Interface Guidelines specifies that we shouldn't do hover buttons becuase of touch screens

**Comment by loulou64490** [comment]
ho yes, you're right
