### ISSUE TITLE
esc exit message edition without saving

### ISSUE THREAD

**Issue by loulou64490** [Jeffser/Alpaca#243]
or add button cancel/save under the editor

**Comment by Jeffser** [comment]
Sorry I didn't answer this earlier, it slipped my mind,
I added a send button, I might also add the cancel button today

![image](https://github.com/user-attachments/assets/053a3d57-e886-41da-8c85-1aa6c1b8adfb)

**Comment by Jeffser** [comment]
Nah it wasn't that hard, I added a save and cancel buttons, they are now at the bottom of the message box so it looks nicer, escape and enter also cancels and saves the message respectively 

![image](https://github.com/user-attachments/assets/e926a60f-9beb-4816-ae93-7f0cd688a3bb)

https://github.com/Jeffser/Alpaca/commit/70c183c71db572ae523afb4a7d84fc1b80d4e1c9
