### ISSUE TITLE
Freeze when setting remote connection is enabled and the remote url is invalid

### ISSUE THREAD

**Issue by imbev** [Jeffser/Alpaca#25]
When the remote connection setting is enabled and the remote URL is not valid, Alpaca becomes unresponsive

https://github.com/Jeffser/Alpaca/assets/105524473/7f7dddb4-3cde-4e86-8b59-1a171f928a6e

**Comment by Jeffser** [comment]
Will fix for next version

**Comment by Jeffser** [comment]
I forgot to change the url when the user switches connection :3 
But it should work now :D
https://github.com/Jeffser/Alpaca/commit/77904b3dd2eb099eceedc3173c063586502e937e

**Comment by Jeffser** [comment]
https://github.com/Jeffser/Alpaca/commit/1a04082564221c19700e7a110735c434d322eb08

Nooow it works
