### ISSUE TITLE
Can't find new models

### ISSUE THREAD

**Issue by ominoussage** [Jeffser/Alpaca#254]
Some models have already come out like Gemma 2 2b and Phi-3.5 3b but I can't find them when searching from "Manage Models". They're already available and searchable from Ollama. They should be showing up.

**Comment by Jeffser** [comment]
Hi, the list of available models is updated manually so that Alpaca connects to the internet as little as possible, if you want to install unlisted models use the '+' icon on the model manager and add a model by name
