### ISSUE TITLE
Send message with Enter

### ISSUE THREAD

**Issue by imbev** [Jeffser/Alpaca#26]
The current behavior is that Enter inserts a newline, Ctrl-Enter sends the message.

I suggest that the behavior be changed so that Enter sends the message, and Shift-Enter inserts a newline. This would bring the behavior in line with mainstream instant messaging apps.

**Comment by Jeffser** [comment]
Hi again thanks for the feedback, I will change it tomorrow if I get some free time

**Comment by imbev** [comment]
Thank you for your work, Alpaca is a great project!

**Comment by Jeffser** [comment]
thanks I appreciate it a lot

**Comment by Jeffser** [comment]
Btw I'm making a 'thank you' section on the readme, would you like me to include you for your feature requests and support?

**Comment by imbev** [comment]
If you'd like, thank you.

**Comment by Jeffser** [comment]
I'm not sure if I can do this, there's no way of capturing every keystroke from the entry as far as I can see

**Comment by imbev** [comment]
How is Ctrl-Enter currently captured?

**Comment by Jeffser** [comment]
It's a keyboard shortcut on the main window, it's not limited to the entry

**Comment by Jeffser** [comment]
I could make the shortcut just enter, problem is that I can't change '\n' to shift+enter

**Comment by imbev** [comment]
Would it be possible to treat it as a keyboard shortcut on the main window, but only insert the newline into the text input when the text input is selected?

**Comment by Jeffser** [comment]
that I don't know, let me try

**Comment by Jeffser** [comment]
I'm so dumb, textview by default treats shift+enter as a new line, I just needed to remove ctrl from the shortcut and it works perfectly 💀 

https://github.com/Jeffser/Alpaca/commit/913a7a0b394af3e52d7291c7bb25d774a045ed34
