### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by MehrzweckMandala** [Jeffser/Alpaca#260]
### A German translation would be great, simply as a quality of life feature. 

I saw the discussion page about translations and I would continue to work on it.

Stay hydrated and have a great day! ;)

#153

**Comment by Jeffser** [comment]
just give me a second to update all the translation files

**Comment by Jeffser** [comment]
The file is ready, thanks for the help

https://github.com/Jeffser/Alpaca/commit/377adc8699ef763c72af1e548c1df44657ad5175
