### ISSUE TITLE
Add instructions (how to compile / build) to README.MD

### ISSUE THREAD

**Issue by MehrzweckMandala** [Jeffser/Alpaca#268]
**Is your feature request related to a problem? Please describe.**
Maybe my suggestion is nonsensical, but wouldn't it make sense to add a “howto build” instruction to the README.MD?

Context:
As a complete amateur when it comes to the Python ( GUI / Gtk ) and Linux (Flatpak) ecosystem, I was not able to build the application after cloning the project.

It may be that this option is not desired.
Nevertheless, I wanted to test some code changes in the *.py files, but if I am not able (due to lack of knowledge) to run the program afterwards, it is a bit frustrating.

Maybe it is also due to my environment - Fedora Workstation 40 GNOME - all necessary dependencies would be installed (python, pip, meson, ninja etc)

**Describe the solution you'd like**
Add instructions to README.MD

**Comment by Jeffser** [comment]
https://github.com/Jeffser/Alpaca/commit/80d1149932f781970af4428901b6bf5d31283a6f

Not the best instructions but it's something
