### ISSUE TITLE
Make font inside of code blocks monospace for better readability

### ISSUE THREAD

**Issue by mags0ft** [Jeffser/Alpaca#283]
Hello,

I've noticed that Alpaca uses the standard font inside of code blocks, which makes a lot of code hard to read:

![image](https://github.com/user-attachments/assets/d3a5ee75-12e5-494e-9164-a11983c4b985)

It would be a lot easier to read the code if it used monospace font:

![image](https://github.com/user-attachments/assets/cbaa34e8-2636-4dd6-8727-49c4d8b8ea23)

Thanks! :)

**Comment by Jeffser** [comment]
Hi, thanks for pointing that out, I'll change it
