### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by l29utp0** [Jeffser/Alpaca#29]
Hello, first I'd like to thank you for this program, it's simple enough and looks good, I've encountered the following bug opening.

```
flatpak run com.jeffser.Alpaca 
Traceback (most recent call last):
  File "/app/share/Alpaca/alpaca/main.py", line 43, in do_activate
    win = AlpacaWindow(application=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/Alpaca/alpaca/window.py", line 1001, in __init__
    css_provider.load_from_path(os.path.join(self.app_dir, "share/Alpaca/alpaca/style.css"))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType

```

**Comment by not-a-dev-stein** [comment]
Same thing here, after opening and closing the app a couple of times, it opens the main window, but all I get is this, and none of the controls work.
![image](https://github.com/Jeffser/Alpaca/assets/63420929/dd13131e-9812-46c4-aae2-323071a5a864)

**Comment by Jeffser** [comment]
Hi, it looks like the code stops loading the css file for some reason, I'm going to replace the file with a string, that might fix it

**Comment by Jeffser** [comment]
[This](https://github.com/Jeffser/Alpaca/commit/541b5e032f550b2b0f0e91730ccf1b25f2abf98c) should fix it

Thanks for the report
