### ISSUE TITLE
Add option to download different tags

### ISSUE THREAD

**Issue by imbev** [Jeffser/Alpaca#3]
Currently, only the latest tag is downloadable. The ability to download other tags for each model is important.

**Comment by Jeffser** [comment]
Thanks for the feedback I will work on it tomorrow

**Comment by Jeffser** [comment]
[Done](https://github.com/Jeffser/Alpaca/commit/02acbb2d700e5bd7811cfdba97696e1c7ed332eb)

Thank you for your suggestion, I will publish the change on the next version, it should be available on Flathub in the next few days
