### ISSUE TITLE
CPU usage seems to be stuck at around 64 threads

### ISSUE THREAD

**Issue by privacyadmin** [Jeffser/Alpaca#303]
**Describe the bug**
When using a model bigger than the amount of VRAM, the query is overflowed to the CPU but capped at around 64 threads. RAM usage did not increase as well.

**Expected behavior**
Ideally it should use all available CPU threads. In my case, I have more than 64 CPU threads and the usage is capped at around 33% which is 64 CPU threads

**Comment by Jeffser** [comment]
Hi, you should probably open an issue on [Ollama](https://github.com/ollama/ollama)

**Comment by privacyadmin** [comment]
OK sure. Thanks. I close this ticket then.
