### ISSUE TITLE
Thoughts on applying for GNOME Circle?

### ISSUE THREAD

**Issue by not-a-dev-stein** [Jeffser/Alpaca#31]
The app is in its infancy but it already looks and feels great! You might want to take a look at applying for [GNOME Circle](circle.gnome.org/), as their review is usually really good at picking up design, functionality and accessibility issues that we might miss by using the app as usual.

I believe they usually avoid having ties to AI projects, but since this can and is mainly intended to be used locally and with open models, it has the potential to be a great addition to the project's community curated apps, which could give it even greater visibility!

**Comment by Jeffser** [comment]
I was thinking about that but I'm still not sure if Alpaca is at the level of an official 'Gnome Circle App'

**Comment by not-a-dev-stein** [comment]
The good thing about applying is that they usually give great insight on the issues the project would have to become one. Also, the app is already in great shape, design-wise.

I believe it could be worth a try, but since it could also mean extra work, fixing whatever issues they find, it's always up to you and your availability!

**Comment by Jeffser** [comment]
I'll think about it, thanks for suggesting it

**Comment by Jeffser** [comment]
https://gitlab.gnome.org/Teams/Circle/-/issues/230

I ended up doing it

**Comment by not-a-dev-stein** [comment]
Will close this issue and follow the one on GNOME Gitlab then. Hoping for the best!
