### ISSUE TITLE
[Suggestion] A revamped icon?

### ISSUE THREAD

**Issue by not-a-dev-stein** [Jeffser/Alpaca#32]
This is definitely not a priority nor a criticism of the current icon. It looks good, but I would suggest looking into GNOME's [app-icon-request](https://gitlab.gnome.org/Teams/Design/app-icon-requests/) repo, as their designers could get a really professional-looking icon (and I believe one of their designers did a sketch that could be used as a base a while back, although I couldn't find it). I thought about opening a request there, but it would be something really rude to do without the developers' approval.

I was going to design one to suggest, but my icon design skills are really lacking after changing careers a while back 😅

**Comment by Jeffser** [comment]
You would do me a huge favor if you did either of those things, I made the current icon in like 1 hour without any experience in Inkscape. 

The biggest criticism I got from Flathub volunteers was that it didn't have enough contrast on white backgrounds.

You can go ahead and request an icon if you want to

**Comment by not-a-dev-stein** [comment]
[I created an issue there](https://gitlab.gnome.org/Teams/Design/app-icon-requests/-/issues/55) and sent a concept for what I had in mind, and will send it to the team at their Matrix room, fingers crossed!

**Comment by Jeffser** [comment]
it looks great, thanks for your help, btw could I add you to a thank you section on the Readme?

**Comment by not-a-dev-stein** [comment]
Feel free to do so, I'd love to help with whatever I can!

**Comment by Jeffser** [comment]
I'm going to close the issue, we will see the progress on gitlab
