### ISSUE TITLE
Resizing the window while a response is being rendered causes the application to crash

### ISSUE THREAD

**Issue by plafue** [Jeffser/Alpaca#322]
**Describe the bug**
Resizing the window while a response is being rendered causes the application to crash. 
The `ollama_llama_server ` process keeps running in the background, consuming resources.

**Expected behavior**
The front-end shouldn't crash just by resizing the main window.

**Screenshots**
I could provide a video upon request.

**Debugging information**
Output of `flatpak run com.jeffser.Alpaca &> out.txt`: [out.txt](https://github.com/user-attachments/files/17085108/out.txt)
OS: Ubuntu 24.04.1 LTS

**Comment by Jeffser** [comment]
Hi, thanks for the report, does this happens every time you resize the window or it just happens randomly?

**Comment by plafue** [comment]
I can reproduce it very reliably with output that is longer than four or five lines. I just did it with the `llama3.1:8b` model and the query "suggest books like harry potter":

![image](https://github.com/user-attachments/assets/476b9079-1839-4ac3-a563-0ec27cd4ed8e)

**Comment by Jeffser** [comment]
alright thanks for the response I'll try to reproduce it. I'll keep you updated if I manage to fix it!

**Comment by Jeffser** [comment]
It gives me some errors but it doesn't crash my app.

```
(alpaca:2): Gtk-CRITICAL **: 16:06:43.276: gtk_snapshot_append_layout2: assertion 'PANGO_IS_LAYOUT (layout)' failed

(alpaca:2): Gtk-WARNING **: 16:06:48.153: Trying to snapshot 202409211606202181426aaf60eb21cf47659311d23eada238d5 0x555f4855b8b0 without a current allocation

(alpaca:2): Gtk-WARNING **: 16:06:54.108: Trying to snapshot AdwDialogHost 0x555f46f9a1c0 without a current allocation
```

Maybe it has to do with Pango, it is the way stuff like bold text and titles are rendered in GTK.

Does these errors appear while it is rendering the text or once it finished generating it?

**Comment by plafue** [comment]
The error 

`(alpaca:2): Gtk-CRITICAL **: 10:22:24.513: gtk_snapshot_append_layout2: assertion 'PANGO_IS_LAYOUT (layout)' failed`

appears when it crashes (that is, the "chunks" from the back-end are being rendered and the window is being resized).

I can reproduce it pretty consistently by now :).

**Comment by plafue** [comment]
https://github.com/user-attachments/assets/6a354e90-e20b-404c-ad0c-4a356b204aba

**Comment by Jeffser** [comment]
I changed the way text is rendered by linking it to the main GTK thread
https://github.com/Jeffser/Alpaca/commit/633507fecdf19e9fc04c90228a9e411aaeef0aa6

I wasn't able to replicate this error but hopefully this fixes it

**Comment by plafue** [comment]
Nice! I can confirm that 2.0.5 doesn't crash anymore while resizing :smiley: .
