### ISSUE TITLE
Remember and use last used model

### ISSUE THREAD

**Issue by atirut-w** [Jeffser/Alpaca#323]
**Is your feature request related to a problem? Please describe.**
Alpaca seems to be picking a model to use in a chat pretty much randomly. Downloaded a new one? It now prefers another model. Deleted one? Same.

**Describe the solution you'd like**
When the user pick a model to use, the app should consistently use it across new or all chats until the user pick another.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Jeffser** [comment]
Hi, every chat picks the last model that sent a message in that particular chat, if the chat is new it picks the first model in the list.

I might add an option to change the model that is selected in new chats but I prefer to leave the behavior of each chat defaulting to the last model used

**Comment by Jeffser** [comment]
Last update I added a default model selector on preferences

https://github.com/Jeffser/Alpaca/commit/71375e8a93892c79ebef37ff1c040b606b6569cd
