### ISSUE TITLE
No llama3.2 model available

### ISSUE THREAD

**Issue by K0-RR** [Jeffser/Alpaca#330]
Hi, the app is missing the latest llama version.
https://ollama.com/library

**Comment by olumolu** [comment]
Not a bug not updated to support with this models ollama not even support 90b and 11 b models yet.

**Comment by K0-RR** [comment]
Well it kinda looks like a bug to me since the model is available the the ollama website and (from my understanding) Alpaca searches the ollama repository.

>ollama not even support 90b and 11 b models yet

llama3.2 is a 3b (and 1b) model.

**Comment by olumolu** [comment]
No this is not how this app works this is a offline app this app does not access to that ollama it can only download models that has been mentioned here you can see the code.

**Comment by Jeffser** [comment]
Hi, I'm the developer of the app, Ollama doesn't provide a list of models by itself so I added a file to the app that contains all the available models information. if you want to add a model that isn't included in that list you can press the `+` button in the model manager and then add by name, there  you just need to type `llama3.2:latest` and it should download the model

**Comment by Jeffser** [comment]
The model is now available in the official Alpaca list on version 2.5.0, should be uploaded to Flathub in a couple of hours
