### ISSUE TITLE
"Connection Error" During Remote Conversations

### ISSUE THREAD

**Issue by NN708** [Jeffser/Alpaca#331]
**Describe the bug**
When using Alpaca with a remote connection, it crashes with "Connection Error" after receiving a response.

**Expected behavior**
Continue the conversation without any interruptions.

**Screenshots**
![Screenshot](https://github.com/user-attachments/assets/974f16d6-6690-4fef-83e5-bd310e521043)

**Debugging information**
```
INFO	[window.py | save_history] Saving history
INFO	[connection_handler.py | request] POST : http://localhost:11434/api/chat
ERROR	[window.py | connection_error] Connection error
```

**Comment by william-andersson** [comment]
I have the same issue. (Fedora 40)  Alpaca version: 2.0.5

**Comment by pbrunier** [comment]
Same error here

**Comment by Jeffser** [comment]
Hi, I'm going to download an instance to test this, if it's a simple fix I might have it ready for tonight

**Comment by Jeffser** [comment]
I think I found the error, I'm going to push an update to Flathub

https://github.com/Jeffser/Alpaca/commit/0be0942da3dba15bc3489a85e997ff1326c7ecba

**Comment by NN708** [comment]
@Jeffser Thank you for the quick fix! I can confirm the issue is resolved, so we can close this now.

**Comment by Jeffser** [comment]
Thanks for the report, I'm glad it worked
