### ISSUE TITLE
Markdown is not working correctly

### ISSUE THREAD

**Issue by danielpeterson** [Jeffser/Alpaca#368]
There is an issue with how the markdown is rendered in the chat labels. The translation to Gtk Pango markup seems to work correctly, but the `text_block` class does this in the  `insert_at_end` method:

``` python
def insert_at_end(self, text:str, markdown:bool):
    if markdown:
        self.set_markup(self.get_text() + text)
    else:
        self.set_text(self.get_text() + text)
    self.update_property([1], [self.get_text()])
```

According to the Gtk documentation `label.get_text()` returns the existing text in the widget stripped of any formatting.

*The returned text is as it appears on screen. This does not include any embedded underlines indicating mnemonics or Pango markup.*
https://docs.gtk.org/gtk4/method.Label.get_text.html

This makes the text block loose any formatting associated with previously inserted text when new text is inserted.

This can be easily fixed by changing the implementation to this, keeping track of markdown and text state in a member variable:

``` python
def insert_at_end(self, text:str, markdown:bool):
    self.text += text
    self.markdown = self.markdown or markdown
    if self.markdown:
        self.set_markup(self.text)
    else:
        self.set_text(self.text)
    self.update_property([1], [self.text])
```

I would have turned this into a pull request but I am not sure that this is what was intended with the original code. Also there is an additional issue. The highlighted chat does not render correctly when the application starts even with the above fix. Presumably this text is rendered through some other code path that I have not been able to track down as gnome builder does not seem to support debugging of python code.

In general the pango formatting seems to behave a bit inconsistently but not to the point where it would be impossible to create a solid solution for markup in the Alpaca chat window.

Pango seems to support apply styling to ranges of text through the GtkTextTag class. It works on the text buffers level instead of the widget level. In general it seems like it might be a good idea to work directly with text buffers instead of widgets given the streaming nature of the application. However I have not looked into this in detail.

I can probably look into this and suggest a solution if you can help me with the following:

1. How is the markdown rendering intended to work?
2. How is the document loaded on startup? Can you briefly outline the mechanism and classes involved?
3. What setup do you use to be able to debug the application?

Please keep in mind that I am new to Gtk and Gnome Builder

Thanks!

**Comment by Jeffser** [comment]
You are a 100% right, how didn't I noticed this before?

I edited your code a bit

```PYTHON
    def insert_at_end(self, text:str, markdown:bool):
        self.text += text
        if markdown:
            self.set_markup(self.text)
        else:
            self.set_text(self.text)
        self.update_property([1], [self.text])
```

But now it works great, thanks!

**Comment by Jeffser** [comment]
My bad, I thought I fixed it and then it stopped working haha

**Comment by Jeffser** [comment]
Now it is working

https://github.com/Jeffser/Alpaca/commit/32fdabd8fa31326d635ecfefe6e743d210fee110

Basically what I did is that now every text block has this variable called `raw_text` it saves markdown text with their tags and everything, all the text that isn't considered markdown gets escaped with the help of `GLib.markup_escape_text`, at the end of the text block rendering it grabs all the text that has been saved in `raw_text` and then and only then renders it as markdown. `set_text` is no longer used.

Thanks for the report!

**Comment by PolGZ** [comment]
I am sorry to reopen the issue. I don't really now how github works and I couldn't determine if this change should already have gotten to the flathub 4.0.0 version (but I think it should) and I'm having problems visualizing the markdown on chat for now. Exporting it to md obsidian style seems to work fine. But exporting it just to regular markdown (from chats where it didn't displayed correctly) don't seem to export anything and I get:

```
INFO	[chat_widget.py | export_md] Exporting chat (MD)
Traceback (most recent call last):
  File "/app/share/Alpaca/alpaca/custom_widgets/dialog_widget.py", line 139, in <lambda>
    callback = lambda dialog, task, dropdown=self.get_extra_child(): self.response(dialog.choose_finish(task), dropdown.get_selected_item().get_string())
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/Alpaca/alpaca/custom_widgets/dialog_widget.py", line 145, in response
    self.options[result]['callback'](item)
  File "/app/share/Alpaca/alpaca/window.py", line 895, in <lambda>
    lambda option, options=options: options[option](),
                                    ^^^^^^^^^^^^^^^^^
  File "/app/share/Alpaca/alpaca/window.py", line 887, in <lambda>
    _("Markdown"): lambda chat=chat: chat.export_md(False),
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/Alpaca/alpaca/custom_widgets/chat_widget.py", line 197, in export_md
    markdown.append('<details>\n\n<summary>{} {}</summary>\n\n```TXT\n{}\n```\n\n</details>'.format(emojis[file.file_type], file.get_name(), file.file_content))
                                                                                                    ~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'thought'
```

This chat has an aswer that shows "plain" text, `bash` and `python` codeblocks.

**Comment by Jeffser** [comment]
Hi, I just fixed it, in the future please make a new issue!

Thanks for the report tho
https://github.com/Jeffser/Alpaca/commit/ae80279c0eb55ad5bb6afd7a3714052cde1faeea
