### ISSUE TITLE
Add a command line flag for a new conversation

### ISSUE THREAD

**Issue by castrojo** [Jeffser/Alpaca#374]
Hello, thanks for Alpaca, I love it! 

It'd be nice if the cli could have a flag that would go directly to the new chat screen. 

I'd like to set the copilot key on my next laptop to `flatpak run com.jeffser.Alpaca --new-chat` or something. Thanks!

**Comment by Jeffser** [comment]
Hi, thanks for the suggestion, I'll try to add it for the next version!

**Comment by Jeffser** [comment]
Hi I just implemented this into the app, I'll look into adding more parameters before releasing the next version!
https://github.com/Jeffser/Alpaca/commit/3279fb0d361401aaa0aee1dff3f11d09e6050e93 (commit #1000 btw)

**Comment by Jeffser** [comment]
forgot to mention this here but I also added this new feature called `Quick Ask` it is used with Gnome Search but it can also be invoked by doing `alpaca --ask "message"` it opens a small ephemeral window to just ask that one question, it can be exported to the main Alpaca application with a button after the models answer the question.

I can't think of any more parameters I could add to the app so I'm going to close the issue, if you can think of anything else please tell me, thanks!
