### ISSUE TITLE
Can't copy or delete output that was interrupted

### ISSUE THREAD

**Issue by ihatemakinganaccount** [Jeffser/Alpaca#378]
Alpaca 2.7.0, Fedora 41

Steps:

1. Start a new chat (or continue an existing one)
2. Write a prompt that will take a while to complete
3. As the output is being generated (model is "typing"), stop it with the stop button (or alternatively, close Alpaca)

Result: The message bubble with this unfinished output cannot be deleted, copied, or regenerated

Expected: allow to delete the box, copy the text and restart generation

It seems the model isn't aware of this interrupted output, since when asked, it is unable to refer to it or the prompt that started it, so it shouldn't be affecting further communication, but I can't be really sure it's not taken into account whatsoever. If it is, then not being able to delete it may be affecting further output.

**Comment by ihatemakinganaccount** [comment]
Okay, I see that when the output is stopped, it doesn't get written into the chat log. So, it only stays on the screen in limbo, and disappears after Alpaca restart. The last message is the user's prompt.

As I mention in #379, when the last message is the prompt, I don't see a way to submit it without copying it to a new prompt.

**Comment by razorozx** [comment]
I second this.

**The bug**
Attempting to delete a half-generated prompt is impossible due to the lack of buttons to do so. Happens regardless of model, chat, and re-opening the app.

**Steps:**
1. Enter a prompt
2. Hit the 'send' button for content generation
3. Halt the generation

**Screenshot**
![Screenshot_20241124_122912](https://github.com/user-attachments/assets/478740dd-abea-4fc3-ba7f-5f562adfe63f)

**Comment by Jeffser** [comment]
Hi, I've been looking into this, I changed some code in the past and didn't noticed it broke the connection error process, I've ported the code for the new design and fixed this in these commits

https://github.com/Jeffser/Alpaca/commit/72449db42cde306f5ea7afc2643cb126894185fd
https://github.com/Jeffser/Alpaca/commit/68de01ef090cf93b460c2e1438fa053c37c5ee30

Thanks for the report!
