### ISSUE TITLE
Edit window (for editing a prompt) is tiny

### ISSUE THREAD

**Issue by ihatemakinganaccount** [Jeffser/Alpaca#379]
Alpaca 2.7.0 Flatpak, Fedora 41 (KDE)

Steps:

1. Start a new chat
2. Write a prompt
3. Let the output finish
4. Try to edit your prompt

Sshot: https://imgur.com/a/asxViGA

I actually am able to edit the text, it's just not visible since the field is just a line.

This happens most of the time, with some exceptions I've noticed: if trying to edit while the output is generated, the edit window works normal. Also on 2nd and further edits it looks normal. Sometimes it shows up fine when I press edit, then cancel, then edit again - but not always. It's a bit random, I think.

**Comment by Jeffser** [comment]
Hi, this is an issue with textview elements in GTK don't expand to use the space they are supposed to use, I've been trying to find a way to fix it but haven't been able to

**Comment by Jeffser** [comment]
I ended up overwriting the size of the edit textarea, not the best code over but it does work

https://github.com/Jeffser/Alpaca/commit/2d5d9b76aa9fbe72cc1eeb629e8e02f8e45ea7ec

I also fixed the buttons in a previous commit

**Comment by Jeffser** [comment]
I found what was actually causing the problems with the rendering, basically the textview received text before it was actually shown, using the main thread to set the text fixed it

https://github.com/Jeffser/Alpaca/commit/b969098a5e75afa3ac6f96f4fbce17fe0c02c7ce
