### ISSUE TITLE
Cannot open the app when it is installed as a snap

### ISSUE THREAD

**Issue by umutd3401** [Jeffser/Alpaca#380]
I installed the latest snap package (2.8.0) and I got an error when trying to open the app. I use Ubuntu 24.10.
```
Traceback (most recent call last):
  File "/snap/jeffser-alpaca/x1/usr/bin/alpaca", line 42, in <module>
    resource = Gio.Resource.load(os.path.join(pkgdatadir, 'alpaca.gresource'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-file-error-quark: Failed to open file “/snap/alpaca/current/usr/share/Alpaca/alpaca.gresource”: open() failed: No such file or directory (4)
```

**Comment by Jeffser** [comment]
Hi thanks for reporting this, apparently I was using the wrong snapcraft.yaml to build the app, my bad.

I'm testing some fixes in the yaml file, once everything works I will push the new file.

I will also reupload the snap in the latest release 2.9.0

**Comment by Jeffser** [comment]
Hi again, managed to fix pretty much everything, sorry for taking so long.

The snap package for 2.9.0 in releases should work fine now
