### ISSUE TITLE
[Feat] Vulkan support

### ISSUE THREAD

**Issue by qnixsynapse** [Jeffser/Alpaca#381]
Currently, GPU support is not available for discrete Intel GPUs. However, SYCL and Vulkan are supported in the llama.cpp library, which is wrapped in a Go program named ollama used as a backend in alpaca.

Enabling vulkan will enable these GPUs.

**Comment by Jeffser** [comment]
As far as I know Ollama doesn't provide a way of directly interacting with Vulkan, there's this issue on their repo but I don't think there's anything I can do from Alpaca's side unless I switched over to llama.cpp which I won't

https://github.com/ollama/ollama/issues/2033
