### ISSUE TITLE
Deleting a chat with no name deletes the whole chats folder

### ISSUE THREAD

**Issue by ihatemakinganaccount** [Jeffser/Alpaca#383]
**Describe the bug**

Alpaca 2.8 Flatpak, fedora 41

Some models have a tendency to leave the title of the chat empty e.g. llama3.2(1b-text-q8.0). If you try to delete this chat, the entire chats folder gets deleted.

**Expected behavior**

Something less destructive, I guess. Btw is it even a good idea to store all the chats in one file? This is asking for trouble, I think.

**Debugging information**
`
$ flatpak run --branch=stable --arch=x86_64 --command=alpaca com.jeffser.Alpaca
INFO    [main.py | main] Alpaca version: 2.8.0
INFO    [connection_handler.py | start] Starting Alpaca's Ollama instance...
INFO    [connection_handler.py | start] Started Alpaca's Ollama instance
Error: listen tcp 127.0.0.1:11435: bind: address already in use
INFO    [connection_handler.py | start] client version is 0.4.2

snip

INFO    [window.py | save_history] Saving history
Traceback (most recent call last):
  File "/app/share/Alpaca/alpaca/custom_widgets/dialog_widget.py", line 56, in response
    self.options[result]['callback']()
  File "/app/share/Alpaca/alpaca/window.py", line 723, in <lambda>
    lambda chat_name=chat_name, *_: self.chat_list_box.delete_chat(chat_name),
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/Alpaca/alpaca/custom_widgets/chat_widget.py", line 335, in delete_chat
    self.new_chat()
  File "/app/share/Alpaca/alpaca/custom_widgets/chat_widget.py", line 320, in new_chat
    window.save_history(self.prepend_chat(chat_title))
  File "/app/share/Alpaca/alpaca/window.py", line 574, in save_history
    with open(os.path.join(data_dir, "chats", "chats.json"), "w+", encoding="utf-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.var/app/com.jeffser.Alpaca/data/chats/chats.json'
`

**Comment by ihatemakinganaccount** [comment]
Also, renaming a chat doesn't work. The window reflects the new name, but it's not saved:

`Traceback (most recent call last):
  File "/usr/lib/python3.12/shutil.py", line 847, in move
    os.rename(src, real_dst)
OSError: [Errno 22] Invalid argument: '/home/user/.var/app/com.jeffser.Alpaca/data/chats/' -> '/home/user/.var/app/com.jeffser.Alpaca/data/chats/test'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/share/Alpaca/alpaca/custom_widgets/dialog_widget.py", line 102, in response
    self.options[result]['callback'](*entry_results)
  File "/app/share/Alpaca/alpaca/window.py", line 733, in <lambda>
    lambda new_chat_name, old_chat_name=chat_name, *_: self.chat_list_box.rename_chat(old_chat_name, new_chat_name),
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/Alpaca/alpaca/custom_widgets/chat_widget.py", line 350, in rename_chat
    shutil.move(os.path.join(data_dir, "chats", old_chat_name), os.path.join(data_dir, "chats", new_chat_name))
  File "/usr/lib/python3.12/shutil.py", line 855, in move
    raise Error("Cannot move a directory '%s' into itself"
shutil.Error: Cannot move a directory '/home/user/.var/app/com.jeffser.Alpaca/data/chats/' into itself '/home/user/.var/app/com.jeffser.Alpaca/data/chats/test'.`

**Comment by Jeffser** [comment]
damn you are right, nice find, I'll change it so that it doesn't accept empty names, thanks for the report

**Comment by Jeffser** [comment]
[Fixed](https://github.com/Jeffser/Alpaca/commit/9df58366b8c964e0ee6a36e5d305e91a457a87fe)

Thanks for the report again!
