### ISSUE TITLE
Not able to connect to local ollama server

### ISSUE THREAD

**Issue by Hyphaed** [Jeffser/Alpaca#385]
Have you deleted the option to connect alpaca to local Ollama server?

I do not see the option anymore inside Preferences

**Comment by Jeffser** [comment]
Yeah in previous versions there was an entry widget to input the ip address directly from the preferences menu, that's now done through that new dialog, just switch on 'Use Remote Connection to Ollama'

**Comment by liel-almog** [comment]
Thanks, it works
You should note that somewhere.

**Comment by boredsquirrel** [comment]
yes I agree. This seems like the default URL, and is not a remote one...
