### ISSUE TITLE
llava-llama3 and other llava models do not have image send capacity

### ISSUE THREAD

**Issue by CounterFlow64** [Jeffser/Alpaca#39]
I don't know if this is a bug or not, just checking. The original llava LLM-image model allows you to send images. llava with llama3 for example, does not allow to send images, while I do think it's technically designed for this. 

Edit: this is the case with moondream too. It has image understanding, but only original llava allows sending of images in the GUI

**Comment by Jeffser** [comment]
Hi thabks for the report, you see, I have a hard-coded list for which models support images, right now it only has llava but I will add those to that list for the next release.

I will also check if there's a way to dynamically check if a model can use images or not

**Comment by Jeffser** [comment]
Also, thank you for the donation

**Comment by CounterFlow64** [comment]
Thanks, really appreciate the project btw

**Comment by Jeffser** [comment]
just so you know I made the changes and added a subtitle to every model that can read images, the next update ([0.8.0](https://github.com/Jeffser/Alpaca/releases/tag/0.8.0)) should be available on Flathub in a couple of hours
https://github.com/Jeffser/Alpaca/commit/0c9fd6685b636c674cf82d8fd4ffa6f8d735af5a
