### ISSUE TITLE
Incorrect zh_CN locale causes Chinese display issues

### ISSUE THREAD

**Issue by NekoLOvO** [Jeffser/Alpaca#390]
### Description
I encountered a problem with the language display in Alpaca when using a Chinese system locale  (zh_CN):

When system language is set to _zh_CN.UTF-8_, which is the standard for Simplified Chinese in most Linux distributions, in the locale folder (_/locale/_), there is a file named _zh_CN_, but it seems to be incorrect or non-functional. Based on the GitHub repository, there is only a valid _zh_Hans_ translation file, and no _zh_CN_ translation file should exist. When Alpaca runs with the default system locale (_zh_CN_), it falls back to the default language (English) instead of displaying Chinese. 

**However:**
- Manually setting the environment variable to _zh_Hans.UTF-8_ allows the application to display the correct Chinese interface.
- Renaming the _zh_Hans_ file to _zh_CN_ also resolves the issue, as the application then correctly picks up the Chinese translations.

### Steps to Reproduce

1. Set the system language to _zh_CN.UTF-8_.
2. Start Alpaca without any additional environment variables.
3. Observe that the interface defaults to English instead of Chinese.
4. Set the environment variable explicitly to zh_Hans.UTF-8:
> flatpak run --env=LANG=zh_Hans.UTF-8 com.jeffser.Alpaca
5. The interface displays correctly in Chinese.
6. Alternatively, rename the _zh_Hans_ file to _zh_CN_ in the locale directory and restart Alpaca. This also resolves the issue.

### Environment
Operating System: Arch Linux
System Locale: zh_CN.UTF-8
Alpaca Version: 2.9.0

**Comment by Jeffser** [comment]
Hi thanks for the report, the file was actually named zh_CN before but I believe @8ar10der (one of the Simplified Chinese translators) changed it, I don't actually remember why but I think it should be up to them to decide if we change it back to zh_CN or leave it as it is, or maybe duplicate the file

**Comment by 8ar10der** [comment]
I will take a look, but this does not make sense. 

Hi @NekoLOvO , would you like to share which Desktop Environment are you using?

I tested on Gnome with my archlinux before and it worked.

**Comment by 8ar10der** [comment]
@8ar10der You can assign the issue to me.

**Comment by 8ar10der** [comment]
Fixed in this PR: https://github.com/Jeffser/Alpaca/pull/392

@NekoLOvO Please wait for next release.

**Comment by Jeffser** [comment]
Thanks
