### ISSUE TITLE
Request: refresh model list

### ISSUE THREAD

**Issue by ihatemakinganaccount** [Jeffser/Alpaca#396]
Scenario: using Alpaca with an external Ollama instance. When you create/download a new model, you need to close and restart Alpaca to see the new addition in the list.

It would be nice to have a refresh button to get the new list of models from the instance.

**Comment by Jeffser** [comment]
thanks for the suggestion, I'll try to add a refresh button in the model manager

**Comment by Jeffser** [comment]
Alright I added it when using a remote connection!

https://github.com/Jeffser/Alpaca/commit/bba8babc5f3a3364db78a3bc8f22dd2b0b5b883c
