### ISSUE TITLE
Response regenerated by another model shows old model as author

### ISSUE THREAD

**Issue by ihatemakinganaccount** [Jeffser/Alpaca#397]
Basically:

1. Have at least 2 models installed
2. Write a prompt
3. Have the model generate a response
4. Switch to model no. 2
5. Regenerate the response

Result: the response is "signed" by the first model

Expected: the model that actually generated the response should be signed.

I guess it's silly and you don't have to care, but I thought it's an interesting detail.

**Comment by Jeffser** [comment]
nice find, thanks for reporting it even if it's a small bug, I'll try to fix it!

**Comment by Jeffser** [comment]
Turns out the correct model regenerates the message but the metadata in Alpaca's side didn't change, simple 2 line fix, thanks for the report!

https://github.com/Jeffser/Alpaca/commit/58f9014ceda4a96b81a06b588f60bbef7cd02386
