### ISSUE TITLE
Consider changing names.

### ISSUE THREAD

**Issue by poudink** [Jeffser/Alpaca#4]
KDE has an application called Alpaka: https://invent.kde.org/utilities/alpaka

Just like this application, it is also an Ollama client, except it's using Qt6/Kirigami instead of GTK4/Libadwaita. The names have a single letter difference and are pronounced the same, which is bound the cause confusion.

**Comment by Jeffser** [comment]
My bad I didn't know about Alpaka, I might change the name in the future if I can think of something better, I'm open to suggestions

**Comment by imbev** [comment]
With help from llama3:8b:

- Insight
- LlamaLine
- LLMinate
- LlamaPal
- ModelMate

I prefer LLMinate and Insight out of these

**Comment by imbev** [comment]
Also see https://docs.flathub.org/docs/for-app-authors/maintenance/#end-of-life-rebase

**Comment by Jeffser** [comment]
I like LlamaPal, I will change it

**Comment by imbev** [comment]
I think it does match the requirements, however I'm not a GNOME designer.

You could try asking at https://matrix.to/#/#gnome:gnome.org

**Comment by Jeffser** [comment]
alright let's do this, I'll keep Alpaca, if the developers of Alpaka ask me to change the name I will
