### ISSUE TITLE
Minor improvements to Flathub metadata would be appreciated

### ISSUE THREAD

**Issue by not-a-dev-stein** [Jeffser/Alpaca#40]
Not necessarily a priority thing, but it would be nice to have some improvements to the Flathub page, mainly:

- adding the fact that the app is now adaptative to mobile: https://gitlab.gnome.org/GNOME/gnome-software/-/wikis/software-metadata#user-content-how-to-add-missing-hardware-information
- updating the screenshots to the current state of the app (and having screenshots in light mode would be nice)
- maybe add some information about age ratings?

This is how it currently looks in GNOME Software (the text is in portuguese though, sorry):
![image](https://github.com/Jeffser/Alpaca/assets/63420929/a77d7709-4909-4a60-8b15-12980b2142b0)

**Comment by Jeffser** [comment]
Hi I already pushed the mobile metadata, since the app doesn't have an age rating it stays like that and I will change the screenshots for the next version
