### ISSUE TITLE
Proper MD support (including LaTeX markup)

### ISSUE THREAD

**Issue by janishutz** [Jeffser/Alpaca#410]
**Is your feature request related to a problem? Please describe.**
There are Python libraries that provide MD conversion. I am though not sure how good GTK is at displaying maths. If it is possible, without much tinkering with GTK, could you point me to the location in the code where MD parsing is handled, so I could work on a solution myself potentially as well and open a PR. If some GTK issues need a workaround, I can sadly not help all that much, as my experience with GTK is fairly limited. 

**Describe the solution you'd like**
Parse the output of say Mathstral to actual mathematical formulas. 

**Describe alternatives you've considered**
Another option imo would also be to add a button that says something like "view as LaTeX PDF" and then uses some conversion algorithm to convert the normal output to LaTeX. I could work on that, but the PDF reader-part is something I don't know how to do. Well apart from opening it in an external reader

**Comment by Jeffser** [comment]
Hi, GTK uses Pango Markup, it doesn't have proper latex rendering, I've been testing different ways of rendering latex with images but that might have to wait until next year

**Comment by olumolu** [comment]
https://github.com/Jeffser/Alpaca/issues/272
This issue is a duplicate issue

**Comment by janishutz** [comment]
I did a quick search, but didn't see that one, sorry

**Comment by Jeffser** [comment]
Don't worry, I'll close this as a duplicate but feel free to comment on the original issue
