### ISSUE TITLE
Blank response

### ISSUE THREAD

**Issue by Mavbraz** [Jeffser/Alpaca#416]
**Describe the bug**
I was testing the Llama 3.2 (3B) and asked a question that would request a long response. During the generation of the response, I could see the message being written, but after fully generated it disappeared from my screen.
The only way to see it again was clicking to edit and getting the html generated.
> FYI: I use Manjaro as my OS.

**Expected behavior**
I expect to see the response generated no matter how long it is and if it has HTML or any other markup.

**Screenshots**
![Screenshot From 2024-12-24 11-58-50](https://github.com/user-attachments/assets/5c93d76b-b431-4cb2-90a1-73ac343a72f1)
![Screenshot From 2024-12-24 12-00-24](https://github.com/user-attachments/assets/d39c8793-16c0-48c4-b6cd-2a0e92bff98e)

**Debugging information**
> The debugging information was too long. Due to this, I attached the file below.

[alpaca_debug.txt](https://github.com/user-attachments/files/18240604/alpaca_debug.txt)

**Comment by Jeffser** [comment]
Hi thanks for the report, I just fixed the code in charge of rendering text blocks

https://github.com/Jeffser/Alpaca/commit/689361cee4d3f731598cfa2b1beab353e81888d0

I'm preparing a quick 3.0.1 release that will become available in Flathub in a couple of hours

**Comment by Jeffser** [comment]
I just published 3.0.1 on Flathub, I'm going to close this issue, if you still have the same problem feel free to reopen it
