### ISSUE TITLE
Download Button does not function

### ISSUE THREAD

**Issue by Error504TimeOut** [Jeffser/Alpaca#421]
**Describe the bug**
The download button does not seem to function

**Expected behavior**
A model should be downloadable through the dialog. If a click happens, the following can be seen in the Terminal:
```
 Traceback (most recent call last):
  File "/app/share/Alpaca/alpaca/custom_widgets/model_widget.py", line 546, in <lambda>
    gesture_click.connect("pressed", lambda *_, name=f"{self.get_name()}:{tag_data[0]}" : self.pull_model(name))
                                                                                          ^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/Alpaca/alpaca/custom_widgets/model_widget.py", line 507, in pull_model
    ram = float(os.popen("free -b | awk '/^Mem:/ {print $7}'").read().strip())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: ''

```

**Screenshots**
-/-

**Debugging information**
```
Couldn't find '/home/user/.ollama/id_ed25519'. Generating new private key.
Your new public key is: 

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK2EKQ9Caxx2Uv1N8oNEGm2oozYp7alEktaW3RqambIi

2024/12/25 23:12:23 routes.go:1253: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_DEBUG:true OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://127.0.0.1:11435 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_KV_CACHE_TYPE: OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/home/jarne/.var/app/com.jeffser.Alpaca/data/.ollama/models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://*] OLLAMA_SCHED_SPREAD:false ROCR_VISIBLE_DEVICES: http_proxy: https_proxy: no_proxy:]"
time=2024-12-25T23:12:23.426+01:00 level=INFO source=images.go:757 msg="total blobs: 0"
time=2024-12-25T23:12:23.426+01:00 level=INFO source=images.go:764 msg="total unused blobs removed: 0"
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] POST   /api/pull                 --> github.com/ollama/ollama/server.(*Server).PullHandler-fm (5 handlers)
[GIN-debug] POST   /api/generate             --> github.com/ollama/ollama/server.(*Server).GenerateHandler-fm (5 handlers)
[GIN-debug] POST   /api/chat                 --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (5 handlers)
[GIN-debug] POST   /api/embed                --> github.com/ollama/ollama/server.(*Server).EmbedHandler-fm (5 handlers)
[GIN-debug] POST   /api/embeddings           --> github.com/ollama/ollama/server.(*Server).EmbeddingsHandler-fm (5 handlers)
[GIN-debug] POST   /api/create               --> github.com/ollama/ollama/server.(*Server).CreateHandler-fm (5 handlers)
[GIN-debug] POST   /api/push                 --> github.com/ollama/ollama/server.(*Server).PushHandler-fm (5 handlers)
[GIN-debug] POST   /api/copy                 --> github.com/ollama/ollama/server.(*Server).CopyHandler-fm (5 handlers)
[GIN-debug] DELETE /api/delete               --> github.com/ollama/ollama/server.(*Server).DeleteHandler-fm (5 handlers)
[GIN-debug] POST   /api/show                 --> github.com/ollama/ollama/server.(*Server).ShowHandler-fm (5 handlers)
[GIN-debug] POST   /api/blobs/:digest        --> github.com/ollama/ollama/server.(*Server).CreateBlobHandler-fm (5 handlers)
[GIN-debug] HEAD   /api/blobs/:digest        --> github.com/ollama/ollama/server.(*Server).HeadBlobHandler-fm (5 handlers)
[GIN-debug] GET    /api/ps                   --> github.com/ollama/ollama/server.(*Server).PsHandler-fm (5 handlers)
time=2024-12-25T23:12:23.426+01:00 level=INFO source=routes.go:1304 msg="Listening on 127.0.0.1:11435 (version 0.5.2)"
[GIN-debug] POST   /v1/chat/completions      --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (6 handlers)
[GIN-debug] POST   /v1/completions           --> github.com/ollama/ollama/server.(*Server).GenerateHandler-fm (6 handlers)
[GIN-debug] POST   /v1/embeddings            --> github.com/ollama/ollama/server.(*Server).EmbedHandler-fm (6 handlers)
[GIN-debug] GET    /v1/models                --> github.com/ollama/ollama/server.(*Server).ListHandler-fm (6 handlers)
[GIN-debug] GET    /v1/models/:model         --> github.com/ollama/ollama/server.(*Server).ShowHandler-fm (6 handlers)
[GIN-debug] GET    /                         --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func1 (5 handlers)
[GIN-debug] GET    /api/tags                 --> github.com/ollama/ollama/server.(*Server).ListHandler-fm (5 handlers)
[GIN-debug] GET    /api/version              --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func2 (5 handlers)
[GIN-debug] HEAD   /                         --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func1 (5 handlers)
[GIN-debug] HEAD   /api/tags                 --> github.com/ollama/ollama/server.(*Server).ListHandler-fm (5 handlers)
[GIN-debug] HEAD   /api/version              --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func2 (5 handlers)
time=2024-12-25T23:12:23.426+01:00 level=DEBUG source=common.go:79 msg="runners located" dir=/app/lib/ollama/runners
time=2024-12-25T23:12:23.426+01:00 level=DEBUG source=common.go:123 msg="availableServers : found" file=/app/lib/ollama/runners/cpu_avx/ollama_llama_server
time=2024-12-25T23:12:23.426+01:00 level=DEBUG source=common.go:123 msg="availableServers : found" file=/app/lib/ollama/runners/cpu_avx2/ollama_llama_server
time=2024-12-25T23:12:23.426+01:00 level=DEBUG source=common.go:123 msg="availableServers : found" file=/app/lib/ollama/runners/cuda_v11_avx/ollama_llama_server
time=2024-12-25T23:12:23.426+01:00 level=DEBUG source=common.go:123 msg="availableServers : found" file=/app/lib/ollama/runners/cuda_v12_avx/ollama_llama_server
time=2024-12-25T23:12:23.426+01:00 level=DEBUG source=common.go:123 msg="availableServers : found" file=/app/lib/ollama/runners/rocm_avx/ollama_llama_server
time=2024-12-25T23:12:23.426+01:00 level=INFO source=routes.go:1333 msg="Dynamic LLM libraries" runners="[rocm_avx cpu cpu_avx cpu_avx2 cuda_v11_avx cuda_v12_avx]"
time=2024-12-25T23:12:23.426+01:00 level=DEBUG source=routes.go:1334 msg="Override detection logic by setting OLLAMA_LLM_LIBRARY"
time=2024-12-25T23:12:23.426+01:00 level=DEBUG source=sched.go:105 msg="starting llm scheduler"
time=2024-12-25T23:12:23.426+01:00 level=INFO source=gpu.go:226 msg="looking for compatible GPUs"
time=2024-12-25T23:12:23.428+01:00 level=DEBUG source=gpu.go:99 msg="searching for GPU discovery libraries for NVIDIA"
time=2024-12-25T23:12:23.428+01:00 level=DEBUG source=gpu.go:517 msg="Searching for GPU library" name=libcuda.so*
time=2024-12-25T23:12:23.428+01:00 level=DEBUG source=gpu.go:543 msg="gpu library search" globs="[/app/lib/ollama/libcuda.so* /app/lib/ollama/libcuda.so* /app/lib/libcuda.so* /usr/lib/x86_64-linux-gnu/GL/default/lib/libcuda.so* /usr/lib/x86_64-linux-gnu/openh264/extra/libcuda.so* /usr/lib/x86_64-linux-gnu/openh264/extra/libcuda.so* /usr/lib/sdk/llvm15/lib/libcuda.so* /usr/lib/x86_64-linux-gnu/GL/default/lib/libcuda.so* /usr/lib/ollama/libcuda.so* /app/plugins/AMD/lib/ollama/libcuda.so* /usr/local/cuda*/targets/*/lib/libcuda.so* /usr/lib/*-linux-gnu/nvidia/current/libcuda.so* /usr/lib/*-linux-gnu/libcuda.so* /usr/lib/wsl/lib/libcuda.so* /usr/lib/wsl/drivers/*/libcuda.so* /opt/cuda/lib*/libcuda.so* /usr/local/cuda/lib*/libcuda.so* /usr/lib*/libcuda.so* /usr/local/lib*/libcuda.so*]"
time=2024-12-25T23:12:23.430+01:00 level=DEBUG source=gpu.go:577 msg="discovered GPU libraries" paths=[]
time=2024-12-25T23:12:23.430+01:00 level=DEBUG source=gpu.go:517 msg="Searching for GPU library" name=libcudart.so*
time=2024-12-25T23:12:23.430+01:00 level=DEBUG source=gpu.go:543 msg="gpu library search" globs="[/app/lib/ollama/libcudart.so* /app/lib/ollama/libcudart.so* /app/lib/libcudart.so* /usr/lib/x86_64-linux-gnu/GL/default/lib/libcudart.so* /usr/lib/x86_64-linux-gnu/openh264/extra/libcudart.so* /usr/lib/x86_64-linux-gnu/openh264/extra/libcudart.so* /usr/lib/sdk/llvm15/lib/libcudart.so* /usr/lib/x86_64-linux-gnu/GL/default/lib/libcudart.so* /usr/lib/ollama/libcudart.so* /app/plugins/AMD/lib/ollama/libcudart.so* /app/lib/ollama/libcudart.so* /app/lib/ollama/libcudart.so* /usr/local/cuda/lib64/libcudart.so* /usr/lib/x86_64-linux-gnu/nvidia/current/libcudart.so* /usr/lib/x86_64-linux-gnu/libcudart.so* /usr/lib/wsl/lib/libcudart.so* /usr/lib/wsl/drivers/*/libcudart.so* /opt/cuda/lib64/libcudart.so* /usr/local/cuda*/targets/aarch64-linux/lib/libcudart.so* /usr/lib/aarch64-linux-gnu/nvidia/current/libcudart.so* /usr/lib/aarch64-linux-gnu/libcudart.so* /usr/local/cuda/lib*/libcudart.so* /usr/lib*/libcudart.so* /usr/local/lib*/libcudart.so*]"
time=2024-12-25T23:12:23.431+01:00 level=DEBUG source=gpu.go:577 msg="discovered GPU libraries" paths="[/app/lib/ollama/libcudart.so.11.3.109 /app/lib/ollama/libcudart.so.12.4.127]"
CUDA driver version: 12-7
time=2024-12-25T23:12:23.548+01:00 level=DEBUG source=gpu.go:149 msg="detected GPUs" library=/app/lib/ollama/libcudart.so.11.3.109 count=1
[GPU-047ee891-d9d2-c48e-5c03-6799b3e9238a] CUDA totalMem 6020923392
[GPU-047ee891-d9d2-c48e-5c03-6799b3e9238a] CUDA freeMem 4937547776
[GPU-047ee891-d9d2-c48e-5c03-6799b3e9238a] CUDA usedMem 0
[GPU-047ee891-d9d2-c48e-5c03-6799b3e9238a] Compute Capability 7.5
time=2024-12-25T23:12:23.712+01:00 level=DEBUG source=amd_linux.go:421 msg="amdgpu driver not detected /sys/module/amdgpu"
releasing cudart library
time=2024-12-25T23:12:23.783+01:00 level=INFO source=types.go:131 msg="inference compute" id=GPU-047ee891-d9d2-c48e-5c03-6799b3e9238a library=cuda variant=v11 compute=7.5 driver=0.0 name="" total="5.6 GiB" available="4.6 GiB"
[GIN] 2024/12/25 - 23:12:23 | 200 |     208.882µs |       127.0.0.1 | GET      "/api/tags"

```

**Comment by Jeffser** [comment]
Hi, thanks for the report, could you check if the command `free` works in  your system? if not you probably need to install that

**Comment by Error504TimeOut** [comment]
No, `free` does work.

**Comment by Jeffser** [comment]
alright, I'll change how that works to prevent that error

**Comment by kuro-codes** [comment]
I can confirm this bug.
Installed through flatpak.
Download button does not show any sign of functionality. Did work in previous versions.

`Couldn't find '/var/home/kuro/.ollama/id_ed25519'. Generating new private key.
Your new public key is: 

ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGoo/mLpLc+5zIkepk/3ULyac0svpMwOkrHBWdVCiIUY

2024/12/25 23:24:13 routes.go:1253: INFO server config env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_DEBUG:true OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://127.0.0.1:11435 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_KV_CACHE_TYPE: OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:/var/home/kuro/.var/app/com.jeffser.Alpaca/data/.ollama/models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:0 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://*] OLLAMA_SCHED_SPREAD:false ROCR_VISIBLE_DEVICES: http_proxy: https_proxy: no_proxy:]"
time=2024-12-25T23:24:13.763+01:00 level=INFO source=images.go:757 msg="total blobs: 25"
time=2024-12-25T23:24:13.763+01:00 level=INFO source=images.go:764 msg="total unused blobs removed: 0"
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
time=2024-12-25T23:24:13.764+01:00 level=INFO source=routes.go:1304 msg="Listening on 127.0.0.1:11435 (version 0.5.2)"
time=2024-12-25T23:24:13.764+01:00 level=DEBUG source=common.go:79 msg="runners located" dir=/app/lib/ollama/runners

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)
time=2024-12-25T23:24:13.764+01:00 level=DEBUG source=common.go:123 msg="availableServers : found" file=/app/lib/ollama/runners/cpu_avx/ollama_llama_server
time=2024-12-25T23:24:13.764+01:00 level=DEBUG source=common.go:123 msg="availableServers : found" file=/app/lib/ollama/runners/cpu_avx2/ollama_llama_server
time=2024-12-25T23:24:13.764+01:00 level=DEBUG source=common.go:123 msg="availableServers : found" file=/app/lib/ollama/runners/cuda_v11_avx/ollama_llama_server
time=2024-12-25T23:24:13.764+01:00 level=DEBUG source=common.go:123 msg="availableServers : found" file=/app/lib/ollama/runners/cuda_v12_avx/ollama_llama_server
time=2024-12-25T23:24:13.764+01:00 level=DEBUG source=common.go:123 msg="availableServers : found" file=/app/lib/ollama/runners/rocm_avx/ollama_llama_server

time=2024-12-25T23:24:13.764+01:00 level=INFO source=routes.go:1333 msg="Dynamic LLM libraries" runners="[cpu_avx cpu_avx2 cuda_v11_avx cuda_v12_avx rocm_avx cpu]"
time=2024-12-25T23:24:13.764+01:00 level=DEBUG source=routes.go:1334 msg="Override detection logic by setting OLLAMA_LLM_LIBRARY"
[GIN-debug] POST   /api/pull                 --> github.com/ollama/ollama/server.(*Server).PullHandler-fm (5 handlers)
[GIN-debug] POST   /api/generate             --> github.com/ollama/ollama/server.(*Server).GenerateHandler-fm (5 handlers)
[GIN-debug] POST   /api/chat                 --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (5 handlers)
time=2024-12-25T23:24:13.764+01:00 level=DEBUG source=sched.go:105 msg="starting llm scheduler"
time=2024-12-25T23:24:13.764+01:00 level=INFO source=gpu.go:226 msg="looking for compatible GPUs"
[GIN-debug] POST   /api/embed                --> github.com/ollama/ollama/server.(*Server).EmbedHandler-fm (5 handlers)
[GIN-debug] POST   /api/embeddings           --> github.com/ollama/ollama/server.(*Server).EmbeddingsHandler-fm (5 handlers)
[GIN-debug] POST   /api/create               --> github.com/ollama/ollama/server.(*Server).CreateHandler-fm (5 handlers)
[GIN-debug] POST   /api/push                 --> github.com/ollama/ollama/server.(*Server).PushHandler-fm (5 handlers)
[GIN-debug] POST   /api/copy                 --> github.com/ollama/ollama/server.(*Server).CopyHandler-fm (5 handlers)
[GIN-debug] DELETE /api/delete               --> github.com/ollama/ollama/server.(*Server).DeleteHandler-fm (5 handlers)
[GIN-debug] POST   /api/show                 --> github.com/ollama/ollama/server.(*Server).ShowHandler-fm (5 handlers)
[GIN-debug] POST   /api/blobs/:digest        --> github.com/ollama/ollama/server.(*Server).CreateBlobHandler-fm (5 handlers)
[GIN-debug] HEAD   /api/blobs/:digest        --> github.com/ollama/ollama/server.(*Server).HeadBlobHandler-fm (5 handlers)
[GIN-debug] GET    /api/ps                   --> github.com/ollama/ollama/server.(*Server).PsHandler-fm (5 handlers)
[GIN-debug] POST   /v1/chat/completions      --> github.com/ollama/ollama/server.(*Server).ChatHandler-fm (6 handlers)
[GIN-debug] POST   /v1/completions           --> github.com/ollama/ollama/server.(*Server).GenerateHandler-fm (6 handlers)
[GIN-debug] POST   /v1/embeddings            --> github.com/ollama/ollama/server.(*Server).EmbedHandler-fm (6 handlers)
[GIN-debug] GET    /v1/models                --> github.com/ollama/ollama/server.(*Server).ListHandler-fm (6 handlers)
[GIN-debug] GET    /v1/models/:model         --> github.com/ollama/ollama/server.(*Server).ShowHandler-fm (6 handlers)
[GIN-debug] GET    /                         --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func1 (5 handlers)
[GIN-debug] GET    /api/tags                 --> github.com/ollama/ollama/server.(*Server).ListHandler-fm (5 handlers)
[GIN-debug] GET    /api/version              --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func2 (5 handlers)
[GIN-debug] HEAD   /                         --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func1 (5 handlers)
[GIN-debug] HEAD   /api/tags                 --> github.com/ollama/ollama/server.(*Server).ListHandler-fm (5 handlers)
[GIN-debug] HEAD   /api/version              --> github.com/ollama/ollama/server.(*Server).GenerateRoutes.func2 (5 handlers)
time=2024-12-25T23:24:13.766+01:00 level=DEBUG source=gpu.go:99 msg="searching for GPU discovery libraries for NVIDIA"
time=2024-12-25T23:24:13.766+01:00 level=DEBUG source=gpu.go:517 msg="Searching for GPU library" name=libcuda.so*
time=2024-12-25T23:24:13.766+01:00 level=DEBUG source=gpu.go:543 msg="gpu library search" globs="[/app/lib/ollama/libcuda.so* /app/lib/ollama/libcuda.so* /app/lib/libcuda.so* /usr/lib/x86_64-linux-gnu/GL/default/lib/libcuda.so* /usr/lib/x86_64-linux-gnu/openh264/extra/libcuda.so* /usr/lib/x86_64-linux-gnu/openh264/extra/libcuda.so* /usr/lib/sdk/llvm15/lib/libcuda.so* /usr/lib/x86_64-linux-gnu/GL/default/lib/libcuda.so* /usr/lib/ollama/libcuda.so* /app/plugins/AMD/lib/ollama/libcuda.so* /usr/local/cuda*/targets/*/lib/libcuda.so* /usr/lib/*-linux-gnu/nvidia/current/libcuda.so* /usr/lib/*-linux-gnu/libcuda.so* /usr/lib/wsl/lib/libcuda.so* /usr/lib/wsl/drivers/*/libcuda.so* /opt/cuda/lib*/libcuda.so* /usr/local/cuda/lib*/libcuda.so* /usr/lib*/libcuda.so* /usr/local/lib*/libcuda.so*]"
time=2024-12-25T23:24:13.768+01:00 level=DEBUG source=gpu.go:577 msg="discovered GPU libraries" paths=[]
time=2024-12-25T23:24:13.768+01:00 level=DEBUG source=gpu.go:517 msg="Searching for GPU library" name=libcudart.so*
time=2024-12-25T23:24:13.768+01:00 level=DEBUG source=gpu.go:543 msg="gpu library search" globs="[/app/lib/ollama/libcudart.so* /app/lib/ollama/libcudart.so* /app/lib/libcudart.so* /usr/lib/x86_64-linux-gnu/GL/default/lib/libcudart.so* /usr/lib/x86_64-linux-gnu/openh264/extra/libcudart.so* /usr/lib/x86_64-linux-gnu/openh264/extra/libcudart.so* /usr/lib/sdk/llvm15/lib/libcudart.so* /usr/lib/x86_64-linux-gnu/GL/default/lib/libcudart.so* /usr/lib/ollama/libcudart.so* /app/plugins/AMD/lib/ollama/libcudart.so* /app/lib/ollama/libcudart.so* /app/lib/ollama/libcudart.so* /usr/local/cuda/lib64/libcudart.so* /usr/lib/x86_64-linux-gnu/nvidia/current/libcudart.so* /usr/lib/x86_64-linux-gnu/libcudart.so* /usr/lib/wsl/lib/libcudart.so* /usr/lib/wsl/drivers/*/libcudart.so* /opt/cuda/lib64/libcudart.so* /usr/local/cuda*/targets/aarch64-linux/lib/libcudart.so* /usr/lib/aarch64-linux-gnu/nvidia/current/libcudart.so* /usr/lib/aarch64-linux-gnu/libcudart.so* /usr/local/cuda/lib*/libcudart.so* /usr/lib*/libcudart.so* /usr/local/lib*/libcudart.so*]"
time=2024-12-25T23:24:13.770+01:00 level=DEBUG source=gpu.go:577 msg="discovered GPU libraries" paths="[/app/lib/ollama/libcudart.so.11.3.109 /app/lib/ollama/libcudart.so.12.4.127]"
cudaSetDevice err: 35
time=2024-12-25T23:24:13.774+01:00 level=DEBUG source=gpu.go:593 msg="Unable to load cudart library /app/lib/ollama/libcudart.so.11.3.109: your nvidia driver is too old or missing.  If you have a CUDA GPU please upgrade to run ollama"
cudaSetDevice err: 35
time=2024-12-25T23:24:13.778+01:00 level=DEBUG source=gpu.go:593 msg="Unable to load cudart library /app/lib/ollama/libcudart.so.12.4.127: your nvidia driver is too old or missing.  If you have a CUDA GPU please upgrade to run ollama"
time=2024-12-25T23:24:13.778+01:00 level=WARN source=amd_linux.go:61 msg="ollama recommends running the https://www.amd.com/en/support/linux-drivers" error="amdgpu version file missing: /sys/module/amdgpu/version stat /sys/module/amdgpu/version: no such file or directory"
time=2024-12-25T23:24:13.778+01:00 level=DEBUG source=amd_linux.go:102 msg="evaluating amdgpu node /sys/class/kfd/kfd/topology/nodes/0/properties"
time=2024-12-25T23:24:13.778+01:00 level=DEBUG source=amd_linux.go:122 msg="detected CPU /sys/class/kfd/kfd/topology/nodes/0/properties"
time=2024-12-25T23:24:13.778+01:00 level=DEBUG source=amd_linux.go:102 msg="evaluating amdgpu node /sys/class/kfd/kfd/topology/nodes/1/properties"
time=2024-12-25T23:24:13.778+01:00 level=DEBUG source=amd_linux.go:207 msg="mapping amdgpu to drm sysfs nodes" amdgpu=/sys/class/kfd/kfd/topology/nodes/1/properties vendor=4098 device=29824 unique_id=0
time=2024-12-25T23:24:13.779+01:00 level=DEBUG source=amd_linux.go:241 msg=matched amdgpu=/sys/class/kfd/kfd/topology/nodes/1/properties drm=/sys/class/drm/card1/device
time=2024-12-25T23:24:13.779+01:00 level=DEBUG source=amd_linux.go:319 msg="amdgpu memory" gpu=0 total="16.0 GiB"
time=2024-12-25T23:24:13.779+01:00 level=DEBUG source=amd_linux.go:320 msg="amdgpu memory" gpu=0 available="14.9 GiB"
time=2024-12-25T23:24:13.779+01:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /app/lib/ollama"
time=2024-12-25T23:24:13.780+01:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /app/lib"
time=2024-12-25T23:24:13.780+01:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /usr/lib/x86_64-linux-gnu/GL/default/lib"
time=2024-12-25T23:24:13.780+01:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /usr/lib/x86_64-linux-gnu/openh264/extra"
time=2024-12-25T23:24:13.780+01:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /usr/lib/x86_64-linux-gnu/openh264/extra"
time=2024-12-25T23:24:13.780+01:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /usr/lib/sdk/llvm15/lib"
time=2024-12-25T23:24:13.780+01:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /usr/lib/x86_64-linux-gnu/GL/default/lib"
time=2024-12-25T23:24:13.780+01:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /usr/lib/ollama"
time=2024-12-25T23:24:13.780+01:00 level=DEBUG source=amd_common.go:18 msg="evaluating potential rocm lib dir /app/plugins/AMD/lib/ollama"
time=2024-12-25T23:24:13.789+01:00 level=DEBUG source=amd_linux.go:373 msg="rocm supported GPUs" types="[gfx1010 gfx1030 gfx1100 gfx1101 gfx1102 gfx900 gfx906 gfx908 gfx90a gfx940 gfx941 gfx942]"
time=2024-12-25T23:24:13.789+01:00 level=INFO source=amd_linux.go:388 msg="amdgpu is supported" gpu=0 gpu_type=gfx1102
time=2024-12-25T23:24:13.790+01:00 level=INFO source=types.go:131 msg="inference compute" id=0 library=rocm variant="" compute=gfx1102 driver=0.0 name=1002:7480 total="16.0 GiB" available="14.9 GiB"
[GIN] 2024/12/25 - 23:24:13 | 200 |    3.475665ms |       127.0.0.1 | GET      "/api/tags"
[GIN] 2024/12/25 - 23:24:13 | 200 |    25.87711ms |       127.0.0.1 | POST     "/api/show"
[GIN] 2024/12/25 - 23:24:13 | 200 |   28.738659ms |       127.0.0.1 | POST     "/api/show"
[GIN] 2024/12/25 - 23:24:13 | 200 |   34.354556ms |       127.0.0.1 | POST     "/api/show"
[GIN] 2024/12/25 - 23:24:13 | 200 |   48.285726ms |       127.0.0.1 | POST     "/api/show"
[GIN] 2024/12/25 - 23:24:13 | 200 |   66.030105ms |       127.0.0.1 | POST     "/api/show"
`

**Comment by Jeffser** [comment]
Fixed: https://github.com/Jeffser/Alpaca/commit/3606c7c12c65c775027865b2826c02a4a4719f2a

Will probably release a new version of Alpaca later today with the fix

**Comment by Error504TimeOut** [comment]
I found the issue. The issue is, that free returns a localized version, meaning that Mem wont be found on the String that `free` returns if the system is i.e. in German

**Comment by Jeffser** [comment]
makes sense, should probably find a better way of getting the available ram

**Comment by Error504TimeOut** [comment]
I think if you want to use free, you could just put LANG=C in front of it.

**Comment by Jeffser** [comment]
I just removed the ram check

https://github.com/Jeffser/Alpaca/commit/4d9faafef9b00a3367e9c547e82f13164d6f7d27

I think it is unreliable because people might be use remote connections, in those cases I could just not show the warning.

Problem is that they might be running a 'remote' connection to the same device to use existing Ollama instances and it wouldn't show the warning then.

Anyways, it's just a headache so I added a warning if the model is big in general
