### ISSUE TITLE
🔧 Development: SQLite transition

### ISSUE THREAD

**Issue by Jeffser** [Jeffser/Alpaca#422]
Hi everyone, today I want to abandon JSON for storing chats, of course the best way of storing large amounts of data would be to use SQL.

I'll be using SQLite because it doesn't require an actual SQL server running in the background just a data.db file to store everything, really practical if you ask me.

# The Plan

I made this quick whiteboard to show the tables and functions I'll need to port to use SQLite.

![image](https://github.com/user-attachments/assets/7dbdff12-4ab2-432f-8044-eea3ce2048d6)

\* `?string` means that it can be null, I took that from how that would work in C#

# Attachments

You might be asking how this button is going to work if I'm not going to store the files directly and instead just save their text.

![image](https://github.com/user-attachments/assets/f276569b-48f7-461e-8e9d-c58f107c410d)

I would probably transform that into an `export` button where it asks where to save the file in the PC, problem with that is that ODT and PDF files will just export the text and nothing more.

Website and YouTube attachments will still behave as expected by opening their URLs

Images will be saved in base64 and converted back to actual images in the interface and when exporting, GTK4 can actually render images from text and Ollama uses base64 to understand images so it's really practical to do it that way.

# Existing Chats

I will transform existing JSON files to the database with a function. I've done this once before where I went from `chatV1` to `chatsV2` (the internal way I referred to chats), that was when I introduced multiple chats.

The function for converting chats will remain in the codebase for a couple of months so that everyone that has chats can get them converted. This process will be fast and opaque to the user, you won't even notice it happen

**Comment by Jeffser** [comment]
Alright I finished the functions needed to convert from `chatsV2 (json)` to `chatsV3 (sqlite)`

https://github.com/Jeffser/Alpaca/commit/3b8449d4baf1394be51e132e4f6cc74e770cee0a

**Comment by Jeffser** [comment]
Finished porting the whole process for loading chats

https://github.com/Jeffser/Alpaca/commit/72ef9c3c02481b24e62bc141c1dd43dc82da4828

**Comment by Jeffser** [comment]
Finished porting new chat

https://github.com/Jeffser/Alpaca/commit/095cd06085adce38163390180dd8090736af1a2a

**Comment by Jeffser** [comment]
Finished porting rename chat

https://github.com/Jeffser/Alpaca/commit/4d68fc2bba88f736cab92eb7e21fd60df3ae6418

**Comment by Jeffser** [comment]
Finished porting delete chat

https://github.com/Jeffser/Alpaca/commit/b9d832268eac54a8314e3db1947ecc9cc4c8d6fb

**Comment by Jeffser** [comment]
Finished porting duplicate chat

https://github.com/Jeffser/Alpaca/commit/293a8a7860c74866573f0b3f0c78f52e06a9008e

**Comment by Jeffser** [comment]
Finished porting edit message

https://github.com/Jeffser/Alpaca/commit/07de900dbcf9e75defca979cd4bc338477f31f78

**Comment by Jeffser** [comment]
Finished porting delete message

https://github.com/Jeffser/Alpaca/commit/8a5356d95c8f97a1ef32fed95cb6e2a310b3d949

**Comment by Jeffser** [comment]
Finished porting send message

https://github.com/Jeffser/Alpaca/commit/db771af41969629c52a40a3c10deb3d12090168d

**Comment by Jeffser** [comment]
Fixed deleting chat and message leaving residual data

https://github.com/Jeffser/Alpaca/commit/f126c87fcd00414c46a5478597906d5bf1445dfd

**Comment by Jeffser** [comment]
Finished porting quick ask

https://github.com/Jeffser/Alpaca/commit/c1145f65b838c8793be09438435a049fbb6998b0

**Comment by Jeffser** [comment]
Finished porting export / import

https://github.com/Jeffser/Alpaca/commit/57c51aba229174f28360f3e76393ac6c461b49a9

Note: Importing via .tar files will stop working in the next version, if you guys have some exported chats, import them now

**Comment by Jeffser** [comment]
Finished porting Markdown exporting, plus there's this new dialog for different options for exporting, who know, I might add more stuff there.

https://github.com/Jeffser/Alpaca/commit/d2335469ab49db1307c565fbbcaa5dcd3c377ff2

![image](https://github.com/user-attachments/assets/542fa16b-72fc-480f-95af-f5d428e43a96)

**Comment by Jeffser** [comment]
Finished porting convert_to_ollama, this function converts the way I save chats in RAM to what Ollama expects

https://github.com/Jeffser/Alpaca/commit/0a95844b2ec87a62edf2b13c07e09fc71b87b572

**Comment by Jeffser** [comment]
Shout out to my playlist for keeping me working for 10 hours straight lmao

**Comment by Jeffser** [comment]
Finished porting send message (attachments)

https://github.com/Jeffser/Alpaca/commit/f8f17319a660ec0e5e89b6f105f025099ee77f95

**Comment by olumolu** [comment]
Sql lite is good but a new project called limbo which is a sql lite alternative and written in rust fully.
https://github.com/tursodatabase/limbo

**Comment by Jeffser** [comment]
come one dude, you see me making like 20 commits porting Alpaca to sqlite and you expect me to just redo it all because of rust?

**Comment by olumolu** [comment]
> come on dude, you see me making like 20 commits porting Alpaca to sqlite and you expect me to just redo it all because of rust?

Obviously no but there is an option.
