### ISSUE TITLE
Latex From QWEN models not loading/rendering.

### ISSUE THREAD

**Issue by ratan00** [Jeffser/Alpaca#432]
**Issue**
Math elements generated by models are not loading properly as human readable text
![image](https://github.com/user-attachments/assets/a319c573-feaf-4c34-b080-2cead3b6f98e)

**Expected behavior**
Should be rendered as human readable as it works in other models, or as it works in their demo
![image](https://github.com/user-attachments/assets/5d3e1602-9741-4d51-9ea3-139cb1d17414)

**Debugging information**
```
```
i have remove debugging info, as such is not deemed important in this case

**Comment by ratan00** [comment]
i found out its Katex rather than Latex for math processing.
i would like to know if Alpaca supports katex. else if there are any plans to support it
Thanks

**Comment by olumolu** [comment]
Duplicate bug report
https://github.com/Jeffser/Alpaca/issues/272
This will be the next feature that is coming in future update
If you can a PR will be highly appreciated.
https://github.com/Jeffser/Alpaca/discussions/412

**Comment by ratan00** [comment]
> Duplicate bug report #272 This will be the next feature that is coming future update If you can a PR will be highly appreciated. #412

Thanks for clarifying,i thought we already had Latex implemented and somehow this was not loading.
so i filed a bug report.
i am sorry about filing PR i have no idea how github works. i am not deep into programming.

**Comment by Jeffser** [comment]
I'll work on Latex support in a couple of weeks

**Comment by Jeffser** [comment]
Closing as duplicate
