### ISSUE TITLE
Auto generate chat titles

### ISSUE THREAD

**Issue by TylerLaBree** [Jeffser/Alpaca#45]
When making a new chat, instead of asking for the user to name it, give them a new, unnamed chat screen, which doesn't yet correspond to a chat button on the left. Allow them to send their first message to a model. Once the LLM finishes responding, have the app ask the model to name the chat in the background, and make the chat button appear on the left with that name.

See ChatGPT for reference.

**Comment by TylerLaBree** [comment]
Do this, but in the background

![image](https://github.com/Jeffser/Alpaca/assets/51167014/3a111a4f-7883-4959-8995-cb1369cf2fbf)

**Comment by Jeffser** [comment]
Hi thanks for the suggestion, right now I'm rewriting a lot of the code, I might do this once I have everything sorted out

**Comment by Jeffser** [comment]
it shouldn't have taken this long, but I finally did it

https://github.com/Jeffser/Alpaca/commit/9c0779a0c7cd57eba58173d36399eda401d32268
