### ISSUE TITLE
New chat doesn't switch properly

### ISSUE THREAD

**Issue by dtlnx** [Jeffser/Alpaca#46]
When creating a new chat, the tab title changes correctly, but the content remains stuck on the previous chat.

![image](https://github.com/Jeffser/Alpaca/assets/149846423/7be4abc4-404c-4368-99bb-520206ae3355)

**Comment by Jeffser** [comment]
I see, thanks for the report, I'm working on it

**Comment by Jeffser** [comment]
[This](https://github.com/Jeffser/Alpaca/commit/92dd56b0c471bee4c54a3276c74db14255b21fc3) should fix it, thanks for the report
