### ISSUE TITLE
Chat window scrolling after initial message.

### ISSUE THREAD

**Issue by dtlnx** [Jeffser/Alpaca#47]
Chat window doesn't full scroll to show model and date/time after the initial message.

![image](https://github.com/Jeffser/Alpaca/assets/149846423/4806cfeb-0afc-487b-be80-6ab229720e7b)

**Comment by Jeffser** [comment]
Hi, thanks for the report, I'm working on it

**Comment by Jeffser** [comment]
[Fixed](https://github.com/Jeffser/Alpaca/commit/25c414faa360b21bffd113e46665bd66eb3ebf65)

Thanks for the report, it is going to be available on the next update
