### ISSUE TITLE
There was an error with the local ollama instance

### ISSUE THREAD

**Issue by ejaz4** [Jeffser/Alpaca#51]
After attempting to download model (doesn't get past metadata stage), I receive this error.
![image](https://github.com/Jeffser/Alpaca/assets/73548455/22edf13e-ac84-40c5-b238-28e29a001bd0)

After this error shows up, clicking Manage Models will crash Alpaca.

**Comment by Jeffser** [comment]
I will try to recreate this, thanks for the report

**Comment by teynav** [comment]
Having the same issue, This is after i have reset the flatpak directory, and downloaded it again
I am getting same error as ejaz4 mentions along with now able to download any model
![image](https://github.com/Jeffser/Alpaca/assets/40721108/e1323241-e8fd-4ea0-b411-02ce66977b1f)

Terminal output is 
```
tarting Alpaca's Ollama instance...
Started Alpaca's Ollama instance
Stopped Alpaca's Ollama instance
Starting Alpaca's Ollama instance...
Started Alpaca's Ollama instance
Stopped Alpaca's Ollama instance
Starting Alpaca's Ollama instance...
Started Alpaca's Ollama instance
```

Regarding program running on port 11435
![image](https://github.com/Jeffser/Alpaca/assets/40721108/f0084c97-f0dd-4acc-833a-56b845068c59)

**Comment by Jeffser** [comment]
So what I think its happening is that sometimes the Ollama instance keeps running even if the app is closed. Could you check if the app is being displayed here?
![image](https://github.com/Jeffser/Alpaca/assets/69224322/cbf2d03d-857d-4a72-9055-f2b4a65d2da6)

**Comment by teynav** [comment]
No nothing is running in background, This thing was open on port even after i uninstalled it and removed flatpak data directory. 

Gnome running background apps don't show it running.

**Comment by teynav** [comment]
> Regarding program running on port 11435

I killed the program at PID 15148 and error disappeared

**Comment by Jeffser** [comment]
I mean, even when you uninstall apps they can sometimes keep running in the background, that's why I asked. What I think is happening is that the ollama instance doesn't stop when the app crashes

**Comment by Jeffser** [comment]
ok for some reason the version that's on Flathub behaves differently than my development version, I just downloaded the app from flathub and got the same error

**Comment by Jeffser** [comment]
I'm going to test everything, once it's ready I will push it to Flathub later today

**Comment by Jeffser** [comment]
Alright I just pushed the changes to Flathub https://buildbot.flathub.org/#/builders/2/builds/62554

It should be available in a couple of hours, sorry for publishing that buggy version, I'll make sure to test everything before publishing
