### ISSUE TITLE
Feature request and bug (I won't leave you alone)

### ISSUE THREAD

**Issue by loulou64490** [Jeffser/Alpaca#53]
Hello, it's me (again)

### Bugs

- [X]  There is a little problem, when I resize the window, the title don't appear well :

![Capture d’écran du 2024-05-28 18-45-22](https://github.com/Jeffser/Alpaca/assets/102870297/e87c6b5f-f8bf-4f73-b2a5-8a3a53bc016a)

- [X] When I delete a chat, the chat frame doesn't reset :

https://github.com/Jeffser/Alpaca/assets/102870297/b117a511-58ad-4695-94d0-25e22aefe108

- [X] And when you delete the last chat, you can send message (It doesn't create automatically a new chat)
- [X] There is two different dialog to delete chat, that's strange, why don't use the same (next video)
- [X] When the windows is small but the sidebar can be displayed, the sidebar is too small and some icon display bad (next video)

https://github.com/Jeffser/Alpaca/assets/102870297/8ae9a623-78a2-4d3b-9ff0-df2c958946fc

- [ ] Some translation ID are missing so we can't translate some part (like the delete chat dialog, and the send button)

### Feature request

- [ ] When creating a chat, or when we launch the app, it would be nice to have an interface like this instead of a blank frame
![Capture d’écran du 2024-05-28 19-12-29](https://github.com/Jeffser/Alpaca/assets/102870297/99ce17e5-77a5-4406-93d3-bbb75f264c81)

- [X] I was asking for a better text entry, like this it's not so far from the Gnome interface guideline (the screenshot is from the Flare app)

![Capture d’écran du 2024-05-28 21-56-23](https://github.com/Jeffser/Alpaca/assets/102870297/6d3b3e22-8117-4d6e-ae01-73fb136b037a)

- [X] Ctrl + N : create new chat

Big thank !

**Comment by Jeffser** [comment]
Hi, thanks for the report and suggestions
The first problem about deleting the last chat is [fixed](https://github.com/Jeffser/Alpaca/commit/f57427e2c44ad59b79b5f4ec4be5524d5e1a0776)

About having two ways of deleting the chat, one clears every message and the other one deletes the chat itself

**Comment by Jeffser** [comment]
![image](https://github.com/Jeffser/Alpaca/assets/69224322/037ce04a-0330-4326-a972-720a0f88ff73)

I also made [this](https://github.com/Jeffser/Alpaca/commit/b8bfd54515aefc38df980bf6eca46cdebc29257c) so that longer chat names get cut off

**Comment by Jeffser** [comment]
I made the ctrl+n new chat shortcut
https://github.com/Jeffser/Alpaca/commit/2645ab3732e792f5c30473f42d0ea9695cb6c832

**Comment by Jeffser** [comment]
This is the new message entry btw

![image](https://github.com/Jeffser/Alpaca/assets/69224322/d1dd5042-d444-4f74-b2f1-a850167ab572)

**Comment by loulou64490** [comment]
> This is the new message entry btw
> 
> ![image](https://github.com/Jeffser/Alpaca/assets/69224322/d1dd5042-d444-4f74-b2f1-a850167ab572)
> 

Much better, you're the goat

**Comment by Jeffser** [comment]
I would like to do that, having one line and making it bigger when the user types multiple lines, but I don't know how. I might try to do it tomorrow

**Comment by Jeffser** [comment]
About using, the paper plane, I know it is the usual icon for that but I'm using the adwaita icon theme (Gnome icons) and that paper airplane isn't included, now, I could just add the SVG of that to the project but I don't feel that's necessary

**Comment by loulou64490** [comment]
Also updated roadmap ( the sleep is a legend )
