### ISSUE TITLE
Installed LLMs aren't being detected

### ISSUE THREAD

**Issue by lunofe** [Jeffser/Alpaca#56]
With the latest update (flatpak 0.9.0), it seems Alpaca can no longer detect my installed LLMs. 

![image](https://github.com/Jeffser/Alpaca/assets/42828197/02eaf036-2fd7-4645-b0ef-97f636efda8d)

![image](https://github.com/Jeffser/Alpaca/assets/42828197/a965a4b5-230f-49da-b64d-1b158992aec7)

**Comment by Jeffser** [comment]
Hi, thanks for the report, are you using a remote instance?

**Comment by Jeffser** [comment]
what I think is happening is that you have a remote instance then you close the app, then the remote instance goes offline, and when you open Alpaca it doesn't give a error message

**Comment by Jeffser** [comment]
I believe the latest update fixes this, if not please open a new issue, thanks
