### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by Fabricio872** [Jeffser/Alpaca#6]
This is an amazing tool to work with very simple and pretty UI but I miss some keyboard shortcuts like Ctrl+C to copy things and Ctrl+Enter to send a message or maybe only enter or something else + Enter.

I am using openSUSE Tumbleweed and the app is installed as Faltpak from Flatstore.

**Comment by Jeffser** [comment]
Sounds like a good idea, I will work on it

**Comment by Jeffser** [comment]
[Done](https://github.com/Jeffser/Alpaca/commit/adef5b5671127a05b1d43345616aacf733091ed4)

I will add more shortcuts when I have free time, thanks for the suggestion!
