### ISSUE TITLE
Icons missing in KDE Plasma 6 desktop

### ISSUE THREAD

**Issue by XotEmBotZ** [Jeffser/Alpaca#67]
**Describe the bug**
The new chat Icon is missing in KDE Plasma 6 (Fedora KDE)

**Expected behavior**
A Icon should be there

**Screenshots**
![alpaca missing icon](https://github.com/Jeffser/Alpaca/assets/92662366/efd94d34-e2e9-483c-ad3a-383a3bc62faa)

Also thanks for quick updating #55

**Comment by Jeffser** [comment]
That's because of Adwaita not being selected as the icon theme I think, I'll include all the icons I use in the app itself

**Comment by topiga** [comment]
No, don't bother. Adwaita published (Adwaita Legacy)[https://gitlab.gnome.org/GNOME/adwaita-icon-theme-legacy]. It should fix your problem on KDE.
Just wait a bit, and try to use icons with the naming scheme of adwaita legacy.

**Comment by Jeffser** [comment]
I'm going to do it anyways, I don't want to ask people to install Adwaita Legacy if they don't want to

**Comment by Jeffser** [comment]
https://github.com/Jeffser/Alpaca/commit/359f28f5c1ade66264a71c036fa05bd5f547eeaf
