### ISSUE TITLE
Impossible to close app (using window controls) if no Ollama installed

### ISSUE THREAD

**Issue by joaquinvacas** [Jeffser/Alpaca#7]
Opening Alpaca for the first time, doesn't let you close the app if you haven't configured ollama yet.

![image](https://github.com/Jeffser/Alpaca/assets/4403750/8841689d-0b78-424a-bc12-80c0d37253a5)

No matter if you try to close it using the "x" on the window, it will spam the "Failed to connect to server" banner without exiting the app itself.

Well, of course it's not impossible, Ctrl + Q or force quitting the app would work, it's not like it crashes or gets stuck, it's that the "x" button on the window doesn't close, as should be expected.

**Comment by Jeffser** [comment]
Alright I'll take a look at that

**Comment by Jeffser** [comment]
that's strange, it works for me, could you tell me which version you are running?

**Comment by joaquinvacas** [comment]
> that's strange, it works for me, could you tell me which version you are running?

I've checked and it's true, the first run it's possible to close the window.
The way to reproduce is follow the first wizard and try to connect, it will show the banner and then every time you try to close the app, it will get stuck in that state (showing the banner each click on the window's "x").

I'm on 0.5.0

**Comment by Jeffser** [comment]
Alright so if you try to connect and gives an error THEN it doesn't close right?

**Comment by Jeffser** [comment]
Yeah you're right, I just found the error, thanks for reporting it

**Comment by Jeffser** [comment]
By the way, I see by the model drop down that you speak spanish, I will translate the app to that language probably today

**Comment by joaquinvacas** [comment]
May I help with that?

Thank you!

**Comment by Jeffser** [comment]
I think I can figure it out, thanks.

Btw, do you speak spanish? I will translate the app to that language probably tomorrow

**Comment by joaquinvacas** [comment]
That's what I meant, I don't do developing (not software) but yes, I do
speak Spanish 😊

**Comment by Jeffser** [comment]
well do you know how to translate apps?
My first language is also spanish but I wouldn't mind some help

**Comment by Jeffser** [comment]
btw I just [fixed](https://github.com/Jeffser/Alpaca/commit/f6cc6ac894bb9a32fe08a9413e8750c0d10a4ea5) the issue

**Comment by Jeffser** [comment]
If you want to help translating it please open a new issue, for now, thanks for reporting the issue!

**Comment by Jeffser** [comment]
Me alegra que te guste la aplicación, ahorita mismo manejo las traducciones al español usando [este archivo](https://github.com/Jeffser/Alpaca/blob/main/po/es.po), ya hice las traducciones así no tienes que preocuparte, pero igual gracias por ofrecer tu ayuda :)
