### ISSUE TITLE
Direct text input when adding a new conversation

### ISSUE THREAD

**Issue by Fray2000** [Jeffser/Alpaca#74]
As of 0.9.1, when creating a new conversation, it is necessary to go press on the input box (prompt text input) to be able to start writing a prompt.

It would be great to have the text cursor directly in the input box, ready for an input and start directly writing right after pressing the button to add a conversation. It would smooth the interaction with the app.

**Comment by Jeffser** [comment]
Sorry it took me so long to answer this suggestion, I didn't see it, I'm not sure if textviews (the element I'm using for text input) can just force focus, I know there are other elements that can do that, I might need to investigate that, thanks for the suggestion

**Comment by Jeffser** [comment]
Sorry it took so long, [it's done](https://github.com/Jeffser/Alpaca/commit/edc3053774cf20e72c02df3fd530aef4cd3122e9)
