### ISSUE TITLE
Manage models: define custom paths & show defaults

### ISSUE THREAD

**Issue by tsilvs** [Jeffser/Alpaca#78]
**Is your feature request related to a problem? Please describe.**

I already have a lot of GiBs of LLMs downloaded on my PC. My connection is metered & slow, storage is limited as well.

I can't afford downloading hundreds of GiBs of data again. It will be slow, expensive & polluting.

**Describe the solution you'd like**

+ Disclose downloads location in UI
+ Let users specify new default model download directory

**Describe alternatives you've considered**

+ Support backups & restores of models

**Additional context**

Alpaca 0.9.2 flatpak from flathub

**Comment by tsilvs** [comment]
Possibly related to #76

**Comment by Jeffser** [comment]
Hi, I don't think I'll be making the download directory modifiable, I prefer it to stay inside the Flatpak directory. For now what you can do if you want to migrate an existing ollama instance to alpaca is [this](https://github.com/Jeffser/Alpaca?tab=readme-ov-file#migrate-ollama-session-to-alpacas-integrated-session)

**Comment by tsilvs** [comment]
> what you can do if you want to migrate an existing ollama instance to alpaca is [this](https://github.com/Jeffser/Alpaca?tab=readme-ov-file#migrate-ollama-session-to-alpacas-integrated-session)

Could be better for UX to add a note somewhere in preferences or list of models about current location for models being `~/.var/app/com.jeffser.Alpaca/data/.ollama`

**Comment by tsilvs** [comment]
@Jeffser another solution idea: what if you add a method of symlinking or hardlinking of models from any user defined directory to `~/.var/app/com.jeffser.Alpaca/data/.ollama`?

**Comment by Jeffser** [comment]
I did a thing 👀

![image](https://github.com/user-attachments/assets/e7633af2-10cd-4038-be01-87e0a54fa333)

**Comment by Jeffser** [comment]
Sooo I have some news for 3.0.0

![image](https://github.com/user-attachments/assets/bb10401c-393f-4140-82c8-46a885db3c4a)

**Comment by Jeffser** [comment]
https://github.com/Jeffser/Alpaca/commit/e450547bea2b184ba44a25f4a7354b02689bdb7f
