### ISSUE TITLE
App crash when stopping model pulling

### ISSUE THREAD

**Issue by tsilvs** [Jeffser/Alpaca#79]
**Describe the bug**
When I start & stop model pulling, application crashes.

**Expected behavior**
When I start & stop model pulling, application should stop pulling & stay opened.

**Additional context**
Alpaca 0.9.2 flatpak from flathub.

**Comment by Jeffser** [comment]
could you run the app using `flatpak run com.jeffser.Alpaca` and send me the output? thanks

**Comment by tsilvs** [comment]
@Jeffser Probably a fluke, can't reproduce it today.

(offtopic: how did you do those nice http request outputs?)

**Comment by Jeffser** [comment]
well if you have this problem again please make a new issue, and those outputs are from Ollama, I didn't do anything
