### ISSUE TITLE
Import/Export chat history format

### ISSUE THREAD

**Issue by imbev** [Jeffser/Alpaca#8]
I see that importing and exporting chat history is on the timeline, however I'd like to suggest the following format:

(new lines encoded as \n)

`[<iso8601 timestamp>] <<User or Pal>> <message>`

Example:

`[2024-05-19T18:43:45.598Z] <User> Hello`
`[2024-05-19T18:43:50.598Z] <Pal> Hi`

This would be both human readable and easy to parse

**Comment by Jeffser** [comment]
Hi thanks for the suggestion, the chats are being handled as a JSON file, that's easier because the app can just send part of the JSON to the Ollama instance, still, thanks for the suggestion, in the future once everything else is sorted out I might implement something similar to this
