### ISSUE TITLE
Why package weights ~300 MiB?

### ISSUE THREAD

**Issue by tsilvs** [Jeffser/Alpaca#81]
Isn't that too big for a text processing app?

Ollama weights ~10 MiB.

**Comment by Jeffser** [comment]
Ollama doesn't weight 10MiB, it weights almost 300MiB

**Comment by Jeffser** [comment]
![image](https://github.com/Jeffser/Alpaca/assets/69224322/c3c299fb-a161-4920-be73-d6a2d3d3ef6e)

**Comment by tsilvs** [comment]
Yeah, sorry, I looked at `.rpm` installer package, not the runner

**Comment by tsilvs** [comment]
@Jeffser wait! Found it!

There is an [OpenSUSE RPM of Ollama](https://opensuse.pkgs.org/tumbleweed/opensuse-oss-x86_64/ollama-0.1.38-2.1.x86_64.rpm.html) ([in "Factory" builds repo](https://build.opensuse.org/package/show/openSUSE:Factory/ollama)).

Maintained by [dimstar](https://build.opensuse.org/users/dimstar_suse) @DimStar77

And the `/usr/bin/ollama` binary in it weights only 30 MiBs!

![image](https://github.com/Jeffser/Alpaca/assets/26058495/d126901f-7810-453c-a42a-9d308e3a774f)

**Comment by Jeffser** [comment]
it is probably an installer for Ollama, not Ollama itself, you see, I need the actual binary so I can sandbox it in Flatpak, using the install scripts from Ollama might work, but it's more work and at the end of the day of the day it ends up weighing the same

**Comment by oritwoen** [comment]
On Arch Linux, ollama weighs 54mb after unpacking and it is not an installer but a binary.

- https://archlinux.org/packages/extra/x86_64/ollama/

The difference in weight results from the fact that in Linux official repositories, ollama uses dynamic linking libraries that are already included in a given system.

Ollama directly from https://github.com/ollama/ollama/releases has a bundle of all libraries to make it compatible with various Linux systems and independent.

**Comment by Jeffser** [comment]
Makes sense, I still won't change it, if the user is able to download models they can download a 300mb binary, I'm not sure how Flatpak interacts with system libraries and stuff like that, there are some binaries that are included with every flatpak but they are very basic

**Comment by oritwoen** [comment]
As for me, it's cool @Jeffser, it's your decision as a maintainer and we have nothing to do with it.

I just mentioned it as an interesting fact for the thread.

Besides, if someone wants to use the app, it won't bother him whether it's flatpak or something else. And even if it bothers someone, there is nothing stopping them from compiling the app on their own computer.

The PKGBUILD I sent you **creates a binary of 0.39MB instead of 300MB** and that's it. With native compilation, it seems that ollama is not bundled anyway. And with native compilation only the "external instance" of ollama works.

![Zrzut ekranu z 2024-06-04 22-23-51](https://github.com/Jeffser/Alpaca/assets/18102267/bc412538-cb62-4718-9925-ac26530fb896)

**Comment by tsilvs** [comment]
@Jeffser @oritwoen 

[`ollama` `0.1.38` `.rpm` from OpenSUSE repo](https://build.opensuse.org/package/show/openSUSE:Factory/ollama) (more links [`@pkgs.org`](https://opensuse.pkgs.org/tumbleweed/opensuse-oss-x86_64/ollama-0.1.38-2.1.x86_64.rpm.html)) lists these dependencies:

+ `/bin/sh`
+ `user(ollama)` & `group(ollama)` (probably meaning that system should have user `ollama:ollama`)
+ `sysuser-shadow` `>= 3.2`
+ `libc.so.6` from `GLIBC` `64bit` `>= 2.2.5` & `<= 2.38`
+ `libm.so.6` from `GLIBC` `64bit` `>= 2.2.5` & `<= 2.29` (which limits `glibc` to be between versions `2.2.5` & `2.29`)
+ `libgcc_s.so.1` from `GCC` `64bit` `=3.0`
+ `libstdc++.so.6` either from:
  + `CXXABI` `64bit` `>= 1.3` & `<= 1.3.13`
  + **OR**
  + `GLIBCXX` `64bit` `>= 3.4` & `<= 3.4.29`

# Arch

<details>

<summary>It's complicated...</summary>

As I understand, the package itself is not an already built binary. I mysef can't run `objdump -x /usr/bin/ollama` - I don't have an Arch environment right now.

[`ollama` `0.1.41` from Arch `extra` repo](https://archlinux.org/packages/extra/x86_64/ollama/) lists these:

+ `git` (for getting sources?)
+ `clblast` (something C++ related?)
+ `cmake` (for building `llama` from `.cpp` sources)
+ `cuda` (for Nvidia GPU support)
+ `rocm-hip-sdk` (for AMD GPU support)
+ `rocm-opencl-sdk` (for AMD GPU support)
+ `go` (for building `ollama` from `.go` sources)

@oritwoen can you clarify what it does? It builds `ollama` on user's device before installation?

## Determining Arch package SO deps from sources

It probably means that we will have to look at [dependency declarations in `llama` sources](https://github.com/ggerganov/llama.cpp):

+ [`CMakePresets.json`](https://github.com/ggerganov/llama.cpp/blob/5921b8f089d3b7bda86aac5a66825df6a6c10603/CMakePresets.json)
+ [`CMakeLists.txt`](https://github.com/ggerganov/llama.cpp/blob/5921b8f089d3b7bda86aac5a66825df6a6c10603/CMakeLists.txt)
+ [`Makefile`](https://github.com/ggerganov/llama.cpp/blob/5921b8f089d3b7bda86aac5a66825df6a6c10603/Makefile)
+ [`cmake`](https://github.com/ggerganov/llama.cpp/tree/5921b8f089d3b7bda86aac5a66825df6a6c10603/cmake)

And at at [dependency declarations in `ollama` sources](https://github.com/ollama/ollama):

+ [`go.mod`](https://github.com/ollama/ollama/blob/476fb8e89242720a7cdd57400ba928de4dde9cc1/go.mod)

</details>

# Flathub 

As mentioned in [dependency management guide](https://docs.flatpak.org/en/latest/dependencies.html), flatpaks can access their own shared dependencies installed as [runtimes](https://docs.flatpak.org/en/latest/available-runtimes.html). If I understood it correctly, `Freedesktop`, `GNOME` & `KDE` runtimes should already contain necessary `glibc`, `gcc` & `cxxabi` shared objects.
