### ISSUE TITLE
GTK Warnings about window elements dimensions boundaries

### ISSUE THREAD

**Issue by tsilvs** [Jeffser/Alpaca#84]
**Describe the bug**

GTK Warnings in termial:

```
(alpaca:2): Gtk-WARNING **: 10:16:43.583: GtkGizmo 0x55fbe1d2e210 (progress) reported min width -2, but sizes must be >= 0

(alpaca:2): Gtk-WARNING **: 10:16:47.685: AdwBreakpointBin 0x55fbe0497c50 (widget) reported min height 95 and natural height 93 in measure() with for_size=-1; natural size must be >= min size
```

**Expected behavior**

No GTK Warnings in terminal, because the causes were fixed.

**Screenshots**

![image](https://github.com/Jeffser/Alpaca/assets/26058495/566a545b-9d22-4569-a38b-948be395d366)

**Additional context**

Alpaca 0.9.2 flatpak from flathub

**Comment by Jeffser** [comment]
Hi, do you have maximize / minimize controls on? I think the topbar doesn't have enough space for all of that if the window is small, that might explain the warnings

**Comment by tsilvs** [comment]
> do you have maximize / minimize controls on?

Yes, they are enabled via GNOME Tweaks.

**Comment by Jeffser** [comment]
yeah it's probably a warning saying that there's not enough space for everything on the titlebar, I might need to redesign it

**Comment by Jeffser** [comment]
Hi, I fixed this for the next release!
