### ISSUE TITLE
reduce the app size

### ISSUE THREAD

**Issue by userforsource** [Jeffser/Alpaca#86]
Reduce the app size is this a electron app reduce the size will make it easier to use

**Comment by loulou64490** [comment]
Hey, this isn't an electron app, and the app is heavy because it comes with Ollama preinstalled, which is heavy 
See : https://github.com/ollama/ollama/releases/latest

**Comment by Jeffser** [comment]
Yeah this isnt an electron app, the app itself is like 10mb almost all of it is Ollama
