### ISSUE TITLE
Just getting errors, not results

### ISSUE THREAD

**Issue by rolandixor** [Jeffser/Alpaca#89]
**Describe the bug**
I'm using 0.9.2, and after installing any model, and asking a question or giving a prompt, I just get a transient error at the top of the input window, then nothing.

**Expected behavior**
Results

**Screenshots**
![Screenshot_20240604_175159](https://github.com/Jeffser/Alpaca/assets/558147/910b6143-081e-47eb-842b-3da508998527)

**Additional context**
Running on Ubuntu 24.04, using the Flatpak version.

**Comment by Jeffser** [comment]
Hi, are you sure you are using 0.9.2? the latest version is 0.9.4

**Comment by Jeffser** [comment]
I just released a new version hopefully it fixes your problem, please install it once it becomes available on Flathub, thanks
