### ISSUE TITLE
Allow downloading models in the Background

### ISSUE THREAD

**Issue by imbev** [Jeffser/Alpaca#9]
Currently downloading a model will prevent all other interaction with the app. This includes closing the app.

I suggest a "Close and continue downloading" button as well as a "stop download" button, perhaps renamed to match the GNOME guidelines.

**Comment by Jeffser** [comment]
Maybe I could just ditch the "Pulling model" dialog, and just add a loading bar on the model being pulled, this might take some time tho

**Comment by Jeffser** [comment]
[Done](https://github.com/Jeffser/Alpaca/commit/d540114ae53bf6c7bc5e12279c44e627abc9b86a)

It was quite hard to remove the previous system but I think it turned out great
