### ISSUE TITLE
0.9.4 | Every request crashing ollama remote session

### ISSUE THREAD

**Issue by BadKiko** [Jeffser/Alpaca#90]
**Describe the bug**
When I write a message and receive a response, I get the error "The remote instance has disconnected"

**Expected behavior**
Continued correct operation

**Screenshots**
![image](https://github.com/Jeffser/Alpaca/assets/53761278/f3c3ef67-7dec-43bc-a9ff-1dcb9a4fd5fa)
![image](https://github.com/Jeffser/Alpaca/assets/53761278/28e819e9-f4a2-4ed4-b17d-1cd6c1f994fd)
![image](https://github.com/Jeffser/Alpaca/assets/53761278/fd30c133-ff13-46d6-b651-bd7f1a9beaca)

**Additional context**
In the previous version everything was fine

**Comment by BadKiko** [comment]
when I did a rollback to 0.9.3 everything started working fine

**Comment by Jeffser** [comment]
Hi, you are using a remote instance right? or it just shows that error?

**Comment by BadKiko** [comment]
I using remote instance of ollama, i think maybe this piece of code make this bug? https://github.com/Jeffser/Alpaca/compare/0.9.3...0.9.4#diff-6b612759ad1849fdde676998a8da94dc5a5401ece7261f1f1ca2ccd98deeadfd

**Comment by Jeffser** [comment]
that can't be it, that's the code used to manage only the local instance

**Comment by BadKiko** [comment]
It's strange, I don't find any differences in the remote part. But in 0.9.4 this does not work, unlike 0.9.3

**Comment by Jeffser** [comment]
that's really weird, I'm going to install an Ollama instance and try to fix it, I should probably add remote instance to my testing before publishing hahaha

**Comment by BadKiko** [comment]
xD Unfortunately, I'm working now, when I get free I'll take the source code and also check where the problem might be.

**Comment by Jeffser** [comment]
This is really, strange, it works fine in my computer, could you run Alpaca using `flatpak run com.jeffser.Alpaca` and sent me the output? of course once you get out of work haha

**Comment by BadKiko** [comment]
unfortunately this is not logged. The logs only go when the local server starts, I used the command flatpak run --devel com.jeffser.Alpaca

**Comment by BadKiko** [comment]
this is so weird, I copied the repo and this error went away xD
maybe this bug is only in the Flatpak version?

**Comment by Jeffser** [comment]
the only version I support is Flatpak so Idk hahaha, I'm going to make a release to fix these errors

**Comment by privacyfreak84** [comment]
This still happens to me

**Comment by privacyfreak84** [comment]
Ran it from terminal and got the following:

`INFO    [main.py | main] Alpaca version: 1.1.1
Exception in thread Thread-2 (generate_chat_title):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/share/Alpaca/alpaca/window.py", line 686, in generate_chat_title
    new_chat_name = json.loads(response.text)["response"].strip().removeprefix("Title: ").removeprefix("title: ").strip('\'"').replace('\n', ' ').title().replace('\'S', '\'s')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
ERROR   [window.py | connection_error] Connection error
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
`

**Comment by privacyfreak84** [comment]
Should I open a new issue for this?

**Comment by Jeffser** [comment]
Hi are you using a remote instance? @privacyfreak84

**Comment by Jeffser** [comment]
I added a check so if the title generation fails it doesn't bring down the whole instance

https://github.com/Jeffser/Alpaca/commit/bd006da0c12bda5afbd546b0df85d5af61902acc
