### ISSUE TITLE
0.9.4 | After update from 0.9.3 getting NoneType error

### ISSUE THREAD

**Issue by BadKiko** [Jeffser/Alpaca#91]
**Describe the bug**
Getting error after updating from 0.9.3 (flatpak)
Traceback (most recent call last):
  File "/app/share/Alpaca/alpaca/main.py", line 42, in do_activate
    win = AlpacaWindow(application=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/Alpaca/alpaca/window.py", line 1162, in __init__
    update_history.update(self)
  File "/app/share/Alpaca/alpaca/update_history.py", line 19, in update
    if 'images' in message:
       ^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by BadKiko** [comment]
Try to update to new version after rollback and get this error xD

**Comment by BadKiko** [comment]
After completely uninstalling and reinstalling everything was fine, but I think it needs to be improved.

**Comment by Jeffser** [comment]
Yeah there might be a problem there, I'll try to replicate this

**Comment by BadKiko** [comment]
I think I can solve this and will make a pull request soon

**Comment by Jeffser** [comment]
I'll do it don't worry about it

**Comment by Jeffser** [comment]
[This](https://github.com/Jeffser/Alpaca/commit/60dd1de39d3cf2cd16ca244d413387a1b3ef29ae) should fix it

**Comment by Jeffser** [comment]
it skips the message if message is None
