### ISSUE TITLE
Add a search bar in "Manage models" page

### ISSUE THREAD

**Issue by spazziale** [Jeffser/Alpaca#98]
**Is your feature request related to a problem? Please describe.**
Searching manually can be annoying

**Describe the solution you'd like**
Adding a search bar in "Manage models" page

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://github.com/Jeffser/Alpaca/assets/46284310/dfbf2e8b-a75d-4556-96a2-9dee0712854e)

**Comment by Jeffser** [comment]
https://github.com/Jeffser/Alpaca/discussions/96#discussioncomment-9682346

Hi thanks for the suggestion, I will add this once I have some free time

**Comment by Jeffser** [comment]
Hi, this is ready for the next release!
