### ISSUE TITLE
Make a sandbox to execute generated code snippets 

### ISSUE THREAD

**Issue by spazziale** [Jeffser/Alpaca#99]
**Is your feature request related to a problem? Please describe.**
Not always generated code is function or let alone able to compile.

**Describe the solution you'd like**
Giving the possibility to users, with flatpak extension, to use compliers and interpreters to execute code can speed up the debugging process.

I assume that redirecting any compiler errors to the model directly can be useful, but this is an additional thing

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Jeffser** [comment]
Hi, thanks for the suggestion but I think this is something way to complex that not a lot of people would find useful, when someone is asking for code to an AI they are probably doing something on a real IDE, they have log messages and debugging and stuff that actually makes coding enjoyable, just running code from an Alpaca isn't practical in my opinion
